# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conexiondron.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images

class Ui_ConexionDron(object):
    def setupUi(self, ConexionDron):
        ConexionDron.setObjectName("ConexionDron")
        ConexionDron.resize(588, 657)
        ConexionDron.setMinimumSize(QtCore.QSize(588, 657))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/paciente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConexionDron.setWindowIcon(icon)
        self.label_17 = QtWidgets.QLabel(ConexionDron)
        self.label_17.setGeometry(QtCore.QRect(30, 510, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_7 = QtWidgets.QLabel(ConexionDron)
        self.label_7.setGeometry(QtCore.QRect(0, 80, 661, 661))
        self.label_7.setMinimumSize(QtCore.QSize(300, 300))
        self.label_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(ConexionDron)
        self.frame.setGeometry(QtCore.QRect(0, 0, 661, 81))
        self.frame.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_Tutor = QtWidgets.QLabel(self.frame)
        self.label_Tutor.setGeometry(QtCore.QRect(0, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_Tutor.setFont(font)
        self.label_Tutor.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_Tutor.setObjectName("label_Tutor")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(470, 0, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("image: url(:/newPrefix/EjerNeutral.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.frame_3 = QtWidgets.QFrame(ConexionDron)
        self.frame_3.setGeometry(QtCore.QRect(0, 80, 651, 8))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_29 = QtWidgets.QLabel(ConexionDron)
        self.label_29.setGeometry(QtCore.QRect(10, 100, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.btnEvaluarConexionDron = QtWidgets.QPushButton(ConexionDron)
        self.btnEvaluarConexionDron.setGeometry(QtCore.QRect(180, 100, 131, 28))
        self.btnEvaluarConexionDron.setObjectName("btnEvaluarConexionDron")
        self.groupBox_3 = QtWidgets.QGroupBox(ConexionDron)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 150, 211, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnElevarDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnElevarDrone.setEnabled(True)
        self.btnElevarDrone.setGeometry(QtCore.QRect(25, 50, 161, 31))
        self.btnElevarDrone.setObjectName("btnElevarDrone")
        self.btnDecenderDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDecenderDrone.setEnabled(True)
        self.btnDecenderDrone.setGeometry(QtCore.QRect(25, 90, 161, 28))
        self.btnDecenderDrone.setObjectName("btnDecenderDrone")
        self.rotarContraRelocj = QtWidgets.QPushButton(self.groupBox_3)
        self.rotarContraRelocj.setGeometry(QtCore.QRect(35, 130, 31, 31))
        self.rotarContraRelocj.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/contraReloj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotarContraRelocj.setIcon(icon1)
        self.rotarContraRelocj.setObjectName("rotarContraRelocj")
        self.btnDerechaDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDerechaDrone.setEnabled(True)
        self.btnDerechaDrone.setGeometry(QtCore.QRect(135, 165, 31, 41))
        self.btnDerechaDrone.setObjectName("btnDerechaDrone")
        self.btnAdelanteDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAdelanteDrone.setEnabled(True)
        self.btnAdelanteDrone.setGeometry(QtCore.QRect(80, 130, 41, 31))
        self.btnAdelanteDrone.setObjectName("btnAdelanteDrone")
        self.btnAterrizarDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAterrizarDrone.setEnabled(True)
        self.btnAterrizarDrone.setGeometry(QtCore.QRect(70, 165, 61, 41))
        self.btnAterrizarDrone.setStyleSheet("")
        self.btnAterrizarDrone.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/despegar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAterrizarDrone.setIcon(icon2)
        self.btnAterrizarDrone.setIconSize(QtCore.QSize(60, 60))
        self.btnAterrizarDrone.setObjectName("btnAterrizarDrone")
        self.btnIsquierdaDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnIsquierdaDrone.setEnabled(True)
        self.btnIsquierdaDrone.setGeometry(QtCore.QRect(35, 165, 31, 41))
        self.btnIsquierdaDrone.setObjectName("btnIsquierdaDrone")
        self.btnAtrasDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAtrasDrone.setEnabled(True)
        self.btnAtrasDrone.setGeometry(QtCore.QRect(80, 210, 41, 31))
        self.btnAtrasDrone.setObjectName("btnAtrasDrone")
        self.rotarRelocj = QtWidgets.QPushButton(self.groupBox_3)
        self.rotarRelocj.setGeometry(QtCore.QRect(135, 130, 31, 31))
        self.rotarRelocj.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/haciaReloj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotarRelocj.setIcon(icon3)
        self.rotarRelocj.setObjectName("rotarRelocj")
        self.groupBox = QtWidgets.QGroupBox(ConexionDron)
        self.groupBox.setGeometry(QtCore.QRect(10, 250, 341, 171))
        self.groupBox.setObjectName("groupBox")
        self.btnValoresPorDefectoConexionDron = QtWidgets.QPushButton(self.groupBox)
        self.btnValoresPorDefectoConexionDron.setGeometry(QtCore.QRect(120, 130, 201, 28))
        self.btnValoresPorDefectoConexionDron.setObjectName("btnValoresPorDefectoConexionDron")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(20, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(20, 90, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.etIpDron = QtWidgets.QLineEdit(self.groupBox)
        self.etIpDron.setGeometry(QtCore.QRect(110, 50, 113, 22))
        self.etIpDron.setStyleSheet("")
        self.etIpDron.setObjectName("etIpDron")
        self.etPuertoDron = QtWidgets.QLineEdit(self.groupBox)
        self.etPuertoDron.setGeometry(QtCore.QRect(110, 90, 113, 22))
        self.etPuertoDron.setStyleSheet("")
        self.etPuertoDron.setObjectName("etPuertoDron")
        self.btnModificarIp = QtWidgets.QPushButton(self.groupBox)
        self.btnModificarIp.setGeometry(QtCore.QRect(230, 45, 93, 28))
        self.btnModificarIp.setObjectName("btnModificarIp")
        self.btnModificarPuerto = QtWidgets.QPushButton(self.groupBox)
        self.btnModificarPuerto.setGeometry(QtCore.QRect(230, 85, 93, 28))
        self.btnModificarPuerto.setObjectName("btnModificarPuerto")
        self.groupBox_2 = QtWidgets.QGroupBox(ConexionDron)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 341, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.cbPorcentajeBateriaDron = QtWidgets.QComboBox(self.groupBox_2)
        self.cbPorcentajeBateriaDron.setGeometry(QtCore.QRect(245, 20, 51, 31))
        self.cbPorcentajeBateriaDron.setObjectName("cbPorcentajeBateriaDron")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.cbPorcentajeBateriaDron.addItem("")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(10, 25, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(10, 70, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lbBateriaDron = QtWidgets.QLabel(self.groupBox_2)
        self.lbBateriaDron.setGeometry(QtCore.QRect(230, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbBateriaDron.setFont(font)
        self.lbBateriaDron.setObjectName("lbBateriaDron")
        self.groupBox_4 = QtWidgets.QGroupBox(ConexionDron)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 420, 551, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setGeometry(QtCore.QRect(20, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setGeometry(QtCore.QRect(20, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_37 = QtWidgets.QLabel(self.groupBox_4)
        self.label_37.setGeometry(QtCore.QRect(20, 100, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_4)
        self.label_38.setGeometry(QtCore.QRect(20, 130, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.etRotarIzquierdaDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etRotarIzquierdaDron.setGeometry(QtCore.QRect(180, 130, 51, 22))
        self.etRotarIzquierdaDron.setStyleSheet("")
        self.etRotarIzquierdaDron.setText("")
        self.etRotarIzquierdaDron.setObjectName("etRotarIzquierdaDron")
        self.etRotarDerechaDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etRotarDerechaDron.setGeometry(QtCore.QRect(180, 100, 51, 22))
        self.etRotarDerechaDron.setStyleSheet("")
        self.etRotarDerechaDron.setText("")
        self.etRotarDerechaDron.setObjectName("etRotarDerechaDron")
        self.etDecenderDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etDecenderDron.setGeometry(QtCore.QRect(180, 70, 51, 22))
        self.etDecenderDron.setStyleSheet("")
        self.etDecenderDron.setText("")
        self.etDecenderDron.setObjectName("etDecenderDron")
        self.etElevarDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etElevarDron.setGeometry(QtCore.QRect(180, 40, 51, 22))
        self.etElevarDron.setStyleSheet("")
        self.etElevarDron.setText("")
        self.etElevarDron.setObjectName("etElevarDron")
        self.label_39 = QtWidgets.QLabel(self.groupBox_4)
        self.label_39.setGeometry(QtCore.QRect(270, 130, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_4)
        self.label_40.setGeometry(QtCore.QRect(270, 70, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_4)
        self.label_41.setGeometry(QtCore.QRect(270, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.etatrasDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etatrasDron.setGeometry(QtCore.QRect(470, 40, 51, 22))
        self.etatrasDron.setStyleSheet("")
        self.etatrasDron.setText("")
        self.etatrasDron.setObjectName("etatrasDron")
        self.label_42 = QtWidgets.QLabel(self.groupBox_4)
        self.label_42.setGeometry(QtCore.QRect(270, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.etIzquierdaDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etIzquierdaDron.setGeometry(QtCore.QRect(470, 130, 51, 22))
        self.etIzquierdaDron.setStyleSheet("")
        self.etIzquierdaDron.setText("")
        self.etIzquierdaDron.setObjectName("etIzquierdaDron")
        self.etDerechaDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etDerechaDron.setGeometry(QtCore.QRect(470, 100, 51, 22))
        self.etDerechaDron.setStyleSheet("")
        self.etDerechaDron.setText("")
        self.etDerechaDron.setObjectName("etDerechaDron")
        self.etAdelanteDron = QtWidgets.QLineEdit(self.groupBox_4)
        self.etAdelanteDron.setGeometry(QtCore.QRect(470, 70, 51, 22))
        self.etAdelanteDron.setStyleSheet("")
        self.etAdelanteDron.setText("")
        self.etAdelanteDron.setObjectName("etAdelanteDron")
        self.pushButton_5brnValoresPorDefectoMovimientosDron = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5brnValoresPorDefectoMovimientosDron.setGeometry(QtCore.QRect(160, 180, 201, 28))
        self.pushButton_5brnValoresPorDefectoMovimientosDron.setObjectName("pushButton_5brnValoresPorDefectoMovimientosDron")
        self.btnAplicarConfiguracionMovimientosDron = QtWidgets.QPushButton(self.groupBox_4)
        self.btnAplicarConfiguracionMovimientosDron.setGeometry(QtCore.QRect(380, 180, 141, 28))
        self.btnAplicarConfiguracionMovimientosDron.setObjectName("btnAplicarConfiguracionMovimientosDron")
        self.label_7.raise_()
        self.label_17.raise_()
        self.frame.raise_()
        self.frame_3.raise_()
        self.label_29.raise_()
        self.btnEvaluarConexionDron.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()

        self.retranslateUi(ConexionDron)
        QtCore.QMetaObject.connectSlotsByName(ConexionDron)

    def retranslateUi(self, ConexionDron):
        _translate = QtCore.QCoreApplication.translate
        ConexionDron.setWindowTitle(_translate("ConexionDron", "Conexión con el dron"))
        self.label_Tutor.setText(_translate("ConexionDron", "Conexión con el dron"))
        self.label_29.setText(_translate("ConexionDron", "Prueba de conexion"))
        self.btnEvaluarConexionDron.setText(_translate("ConexionDron", "Evaluar conexión"))
        self.groupBox_3.setTitle(_translate("ConexionDron", "Control manual de dron"))
        self.btnElevarDrone.setToolTip(_translate("ConexionDron", "Subir Dron"))
        self.btnElevarDrone.setText(_translate("ConexionDron", "Subir dron"))
        self.btnElevarDrone.setShortcut(_translate("ConexionDron", "W"))
        self.btnDecenderDrone.setToolTip(_translate("ConexionDron", "Bajar Dron"))
        self.btnDecenderDrone.setText(_translate("ConexionDron", "Bajar dron"))
        self.btnDecenderDrone.setShortcut(_translate("ConexionDron", "S"))
        self.rotarContraRelocj.setToolTip(_translate("ConexionDron", "Girar Izquierdad Dron"))
        self.rotarContraRelocj.setShortcut(_translate("ConexionDron", "A"))
        self.btnDerechaDrone.setToolTip(_translate("ConexionDron", "Derecha Dron"))
        self.btnDerechaDrone.setText(_translate("ConexionDron", ">"))
        self.btnDerechaDrone.setShortcut(_translate("ConexionDron", "Right"))
        self.btnAdelanteDrone.setToolTip(_translate("ConexionDron", "Adelante Dron"))
        self.btnAdelanteDrone.setText(_translate("ConexionDron", "^"))
        self.btnAdelanteDrone.setShortcut(_translate("ConexionDron", "Up"))
        self.btnAterrizarDrone.setToolTip(_translate("ConexionDron", "Despegar o Aterrizar Dron"))
        self.btnAterrizarDrone.setShortcut(_translate("ConexionDron", "Space"))
        self.btnIsquierdaDrone.setToolTip(_translate("ConexionDron", "Izquierda Dron"))
        self.btnIsquierdaDrone.setText(_translate("ConexionDron", "<"))
        self.btnIsquierdaDrone.setShortcut(_translate("ConexionDron", "Left"))
        self.btnAtrasDrone.setToolTip(_translate("ConexionDron", "Atras Dron"))
        self.btnAtrasDrone.setText(_translate("ConexionDron", "v"))
        self.btnAtrasDrone.setShortcut(_translate("ConexionDron", "Down"))
        self.rotarRelocj.setToolTip(_translate("ConexionDron", "Girar derecha Dron"))
        self.rotarRelocj.setShortcut(_translate("ConexionDron", "D"))
        self.groupBox.setTitle(_translate("ConexionDron", "Parametros de conexión"))
        self.btnValoresPorDefectoConexionDron.setText(_translate("ConexionDron", "Establecer valores por defecto"))
        self.label_31.setText(_translate("ConexionDron", "Ip del dron:"))
        self.label_35.setText(_translate("ConexionDron", "Puerto:"))
        self.etIpDron.setPlaceholderText(_translate("ConexionDron", "192.234.11.2"))
        self.etPuertoDron.setPlaceholderText(_translate("ConexionDron", "5098"))
        self.btnModificarIp.setText(_translate("ConexionDron", "Modificar"))
        self.btnModificarPuerto.setText(_translate("ConexionDron", "Modificar"))
        self.groupBox_2.setTitle(_translate("ConexionDron", "Configuración de bateria del dron"))
        self.cbPorcentajeBateriaDron.setToolTip(_translate("ConexionDron", "Sleección de un paciente"))
        self.cbPorcentajeBateriaDron.setItemText(0, _translate("ConexionDron", "10"))
        self.cbPorcentajeBateriaDron.setItemText(1, _translate("ConexionDron", "15"))
        self.cbPorcentajeBateriaDron.setItemText(2, _translate("ConexionDron", "20"))
        self.cbPorcentajeBateriaDron.setItemText(3, _translate("ConexionDron", "25"))
        self.cbPorcentajeBateriaDron.setItemText(4, _translate("ConexionDron", "30"))
        self.cbPorcentajeBateriaDron.setItemText(5, _translate("ConexionDron", "35"))
        self.cbPorcentajeBateriaDron.setItemText(6, _translate("ConexionDron", "40"))
        self.label_36.setText(_translate("ConexionDron", "Aterrizaje por nivel de bateria:"))
        self.label_30.setText(_translate("ConexionDron", "El porcentaje de bateria es: "))
        self.lbBateriaDron.setText(_translate("ConexionDron", "000%"))
        self.groupBox_4.setTitle(_translate("ConexionDron", "Configuración de la distancia de los movimientos del dron"))
        self.label_32.setText(_translate("ConexionDron", "Elevar dron:"))
        self.label_34.setText(_translate("ConexionDron", "Decender dron:"))
        self.label_37.setText(_translate("ConexionDron", "Rotar a la derecha:"))
        self.label_38.setText(_translate("ConexionDron", "Rotar a la izquierda:"))
        self.etRotarIzquierdaDron.setPlaceholderText(_translate("ConexionDron", "45 °"))
        self.etRotarDerechaDron.setPlaceholderText(_translate("ConexionDron", "45 °"))
        self.etDecenderDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.etElevarDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.label_39.setText(_translate("ConexionDron", "Mover hacia la izquierda:"))
        self.label_40.setText(_translate("ConexionDron", "Mover a hacia adelante:"))
        self.label_41.setText(_translate("ConexionDron", "Mover hacia la derecha:"))
        self.etatrasDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.label_42.setText(_translate("ConexionDron", "Mover hacia atras:"))
        self.etIzquierdaDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.etDerechaDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.etAdelanteDron.setPlaceholderText(_translate("ConexionDron", "30 cm"))
        self.pushButton_5brnValoresPorDefectoMovimientosDron.setText(_translate("ConexionDron", "Establecer valores por defecto"))
        self.btnAplicarConfiguracionMovimientosDron.setText(_translate("ConexionDron", "Aplicar configuración"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConexionDron = QtWidgets.QDialog()
    ui = Ui_ConexionDron()
    ui.setupUi(ConexionDron)
    ConexionDron.show()
    sys.exit(app.exec_())

