# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ejerciciosTerapiaNeurofeedback.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ejercicioTerapeuticos(object):
    def setupUi(self, ejercicioTerapeuticos):
        ejercicioTerapeuticos.setObjectName("ejercicioTerapeuticos")
        ejercicioTerapeuticos.resize(873, 700)
        ejercicioTerapeuticos.setMinimumSize(QtCore.QSize(873, 670))
        self.listImagenesEjercicios = QtWidgets.QListView(ejercicioTerapeuticos)
        self.listImagenesEjercicios.setGeometry(QtCore.QRect(500, 190, 371, 461))
        self.listImagenesEjercicios.setStyleSheet("background-color: rgb(228, 226, 254);")
        self.listImagenesEjercicios.setObjectName("listImagenesEjercicios")
        self.lbEjercicio = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.lbEjercicio.setGeometry(QtCore.QRect(20, 105, 201, 31))
        self.lbEjercicio.setStyleSheet("font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"text-decoration: underline;")
        self.lbEjercicio.setObjectName("lbEjercicio")
        self.btnRealizar = QtWidgets.QPushButton(ejercicioTerapeuticos)
        self.btnRealizar.setGeometry(QtCore.QRect(220, 150, 131, 28))
        self.btnRealizar.setObjectName("btnRealizar")
        self.lbImagenEjercicio = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.lbImagenEjercicio.setGeometry(QtCore.QRect(580, 480, 221, 161))
        self.lbImagenEjercicio.setStyleSheet("image: url(:/newPrefix/EjerNeutral.png);")
        self.lbImagenEjercicio.setText("")
        self.lbImagenEjercicio.setObjectName("lbImagenEjercicio")
        self.label_9 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.label_9.setGeometry(QtCore.QRect(0, 80, 911, 641))
        self.label_9.setMinimumSize(QtCore.QSize(480, 510))
        self.label_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(ejercicioTerapeuticos)
        self.frame.setGeometry(QtCore.QRect(0, 0, 911, 81))
        self.frame.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 601, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_10.setObjectName("label_10")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(790, 0, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("image: url(:/newPrefix/libroNeurofeedback.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.tvEjercicios = QtWidgets.QTableWidget(ejercicioTerapeuticos)
        self.tvEjercicios.setGeometry(QtCore.QRect(20, 190, 471, 461))
        self.tvEjercicios.setMinimumSize(QtCore.QSize(200, 200))
        self.tvEjercicios.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tvEjercicios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvEjercicios.setDragEnabled(False)
        self.tvEjercicios.setRowCount(0)
        self.tvEjercicios.setColumnCount(2)
        self.tvEjercicios.setObjectName("tvEjercicios")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tvEjercicios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tvEjercicios.setHorizontalHeaderItem(1, item)
        self.tvEjercicios.horizontalHeader().setDefaultSectionSize(300)
        self.cbfiltrarEjercicios = QtWidgets.QComboBox(ejercicioTerapeuticos)
        self.cbfiltrarEjercicios.setGeometry(QtCore.QRect(20, 150, 141, 31))
        self.cbfiltrarEjercicios.setObjectName("cbfiltrarEjercicios")
        self.cbfiltrarEjercicios.addItem("")
        self.cbfiltrarEjercicios.addItem("")
        self.btnBuscarTipoEjercicios = QtWidgets.QPushButton(ejercicioTerapeuticos)
        self.btnBuscarTipoEjercicios.setGeometry(QtCore.QRect(160, 150, 31, 31))
        self.btnBuscarTipoEjercicios.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarTipoEjercicios.setIcon(icon)
        self.btnBuscarTipoEjercicios.setObjectName("btnBuscarTipoEjercicios")
        self.frame_2 = QtWidgets.QFrame(ejercicioTerapeuticos)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 911, 8))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(ejercicioTerapeuticos)
        self.frame_3.setGeometry(QtCore.QRect(500, 210, 371, 4))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(20, 130, 198));\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.label_4.setGeometry(QtCore.QRect(500, 190, 368, 20))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(200, 198, 223);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtWidgets.QFrame(ejercicioTerapeuticos)
        self.frame_4.setGeometry(QtCore.QRect(500, 470, 371, 4))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(20, 130, 198));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.label_5.setGeometry(QtCore.QRect(500, 450, 368, 21))
        self.label_5.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(200, 198, 223);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.taDescripcion = QtWidgets.QTextEdit(ejercicioTerapeuticos)
        self.taDescripcion.setEnabled(False)
        self.taDescripcion.setGeometry(QtCore.QRect(500, 290, 351, 151))
        self.taDescripcion.setUndoRedoEnabled(False)
        self.taDescripcion.setPlaceholderText("")
        self.taDescripcion.setObjectName("taDescripcion")
        self.label_3 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.label_3.setGeometry(QtCore.QRect(510, 230, 101, 16))
        self.label_3.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.lbParametro2 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.lbParametro2.setGeometry(QtCore.QRect(590, 260, 271, 20))
        self.lbParametro2.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.lbParametro2.setObjectName("lbParametro2")
        self.label_7 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.label_7.setGeometry(QtCore.QRect(510, 260, 101, 16))
        self.label_7.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.lbParametro1 = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.lbParametro1.setGeometry(QtCore.QRect(590, 230, 271, 20))
        self.lbParametro1.setStyleSheet("font: 63 8pt \"Yu Gothic UI Semibold\";")
        self.lbParametro1.setObjectName("lbParametro1")
        self.lbEjercicioSeecionado = QtWidgets.QLabel(ejercicioTerapeuticos)
        self.lbEjercicioSeecionado.setGeometry(QtCore.QRect(220, 110, 631, 31))
        self.lbEjercicioSeecionado.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"")
        self.lbEjercicioSeecionado.setText("")
        self.lbEjercicioSeecionado.setObjectName("lbEjercicioSeecionado")
        self.label_9.raise_()
        self.listImagenesEjercicios.raise_()
        self.lbEjercicio.raise_()
        self.btnRealizar.raise_()
        self.lbImagenEjercicio.raise_()
        self.frame.raise_()
        self.tvEjercicios.raise_()
        self.cbfiltrarEjercicios.raise_()
        self.btnBuscarTipoEjercicios.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.label_4.raise_()
        self.frame_4.raise_()
        self.label_5.raise_()
        self.taDescripcion.raise_()
        self.label_3.raise_()
        self.lbParametro2.raise_()
        self.label_7.raise_()
        self.lbParametro1.raise_()
        self.lbEjercicioSeecionado.raise_()

        self.retranslateUi(ejercicioTerapeuticos)
        QtCore.QMetaObject.connectSlotsByName(ejercicioTerapeuticos)

    def retranslateUi(self, ejercicioTerapeuticos):
        _translate = QtCore.QCoreApplication.translate
        ejercicioTerapeuticos.setWindowTitle(_translate("ejercicioTerapeuticos", "Dialog"))
        self.lbEjercicio.setText(_translate("ejercicioTerapeuticos", "Ejercicio Seleccionado:"))
        self.btnRealizar.setText(_translate("ejercicioTerapeuticos", "Realizar Ejercicio"))
        self.label_10.setText(_translate("ejercicioTerapeuticos", "Ejercicios de tipo Neurofeedback"))
        item = self.tvEjercicios.horizontalHeaderItem(0)
        item.setText(_translate("ejercicioTerapeuticos", "Nombre"))
        item = self.tvEjercicios.horizontalHeaderItem(1)
        item.setText(_translate("ejercicioTerapeuticos", "Tipo"))
        self.cbfiltrarEjercicios.setItemText(0, _translate("ejercicioTerapeuticos", "Todos"))
        self.cbfiltrarEjercicios.setItemText(1, _translate("ejercicioTerapeuticos", "Dron Tello"))
        self.label_4.setText(_translate("ejercicioTerapeuticos", "Descripción"))
        self.label_5.setText(_translate("ejercicioTerapeuticos", "Imagen"))
        self.taDescripcion.setHtml(_translate("ejercicioTerapeuticos", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Descripción del ejercico....</p></body></html>"))
        self.label_3.setText(_translate("ejercicioTerapeuticos", "Parámetro 1:"))
        self.lbParametro2.setText(_translate("ejercicioTerapeuticos", " -----------------------------------------------"))
        self.label_7.setText(_translate("ejercicioTerapeuticos", "Parámetro 2:"))
        self.lbParametro1.setText(_translate("ejercicioTerapeuticos", " -----------------------------------------------"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ejercicioTerapeuticos = QtWidgets.QDialog()
    ui = Ui_ejercicioTerapeuticos()
    ui.setupUi(ejercicioTerapeuticos)
    ejercicioTerapeuticos.show()
    sys.exit(app.exec_())

