# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recuperarCredenciales.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 502)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/idea-genial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 411, 8))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 81))
        self.frame.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(350, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("image: url(:/newPrefix/key.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 80, 411, 441))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(0, 120, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.etCorreo = QtWidgets.QLineEdit(Dialog)
        self.etCorreo.setGeometry(QtCore.QRect(70, 160, 281, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.etCorreo.setFont(font)
        self.etCorreo.setAutoFillBackground(False)
        self.etCorreo.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(229, 226, 255);")
        self.etCorreo.setAlignment(QtCore.Qt.AlignCenter)
        self.etCorreo.setObjectName("etCorreo")
        self.btnRecuperar = QtWidgets.QPushButton(Dialog)
        self.btnRecuperar.setGeometry(QtCore.QRect(120, 230, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnRecuperar.setFont(font)
        self.btnRecuperar.setStyleSheet("background-color: rgb(180, 255, 199);\n"
"background-color: rgb(200, 198, 223);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.btnRecuperar.setObjectName("btnRecuperar")
        self.labelValidarCorreo = QtWidgets.QLabel(Dialog)
        self.labelValidarCorreo.setGeometry(QtCore.QRect(10, 310, 391, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelValidarCorreo.setFont(font)
        self.labelValidarCorreo.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelValidarCorreo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValidarCorreo.setObjectName("labelValidarCorreo")
        self.labelInstruccion = QtWidgets.QLabel(Dialog)
        self.labelInstruccion.setGeometry(QtCore.QRect(10, 460, 391, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelInstruccion.setFont(font)
        self.labelInstruccion.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.labelInstruccion.setText("")
        self.labelInstruccion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInstruccion.setObjectName("labelInstruccion")
        self.labelImagen = QtWidgets.QLabel(Dialog)
        self.labelImagen.setGeometry(QtCore.QRect(120, 350, 181, 101))
        self.labelImagen.setStyleSheet("image: url(:/newPrefix/load.png);")
        self.labelImagen.setText("")
        self.labelImagen.setObjectName("labelImagen")
        self.label.raise_()
        self.frame_2.raise_()
        self.frame.raise_()
        self.label_7.raise_()
        self.etCorreo.raise_()
        self.btnRecuperar.raise_()
        self.labelValidarCorreo.raise_()
        self.labelInstruccion.raise_()
        self.labelImagen.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Recuperar credenciales"))
        self.label_2.setText(_translate("Dialog", "Recuperar credenciales"))
        self.label_7.setText(_translate("Dialog", "Ingresa tu correo electrónico"))
        self.etCorreo.setPlaceholderText(_translate("Dialog", "Ingresa tu correo electronico"))
        self.btnRecuperar.setText(_translate("Dialog", "Recuperar Credenciales"))
        self.labelValidarCorreo.setText(_translate("Dialog", "verificación de correo electrónico....."))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

