# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporteParaTerapeuta.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 863)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 551, 881))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lb1_2 = QtWidgets.QLabel(self.frame_2)
        self.lb1_2.setGeometry(QtCore.QRect(140, 40, 161, 41))
        self.lb1_2.setStyleSheet("font: 90 8pt \"Segoe UI Black\";")
        self.lb1_2.setObjectName("lb1_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 81, 81))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("image: url(:/newPrefix/idea-genial.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(100, 10, 221, 41))
        self.label_3.setStyleSheet("font: 75 18pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(370, 10, 151, 21))
        self.label_18.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 110, 31, 21))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("image: url(:/newPrefix/reporte.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.lb1_3 = QtWidgets.QLabel(self.frame_2)
        self.lb1_3.setGeometry(QtCore.QRect(40, 110, 161, 21))
        self.lb1_3.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_3.setObjectName("lb1_3")
        self.lb1_4 = QtWidgets.QLabel(self.frame_2)
        self.lb1_4.setGeometry(QtCore.QRect(40, 390, 161, 21))
        self.lb1_4.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_4.setObjectName("lb1_4")
        self.lb1_5 = QtWidgets.QLabel(self.frame_2)
        self.lb1_5.setGeometry(QtCore.QRect(40, 550, 161, 21))
        self.lb1_5.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_5.setObjectName("lb1_5")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(10, 550, 31, 21))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("image: url(:/newPrefix/paciente.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 390, 31, 21))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("image: url(:/newPrefix/terapeuta.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 140, 181, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 8, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 9, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 140, 291, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbAreaCerebro = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbAreaCerebro.setObjectName("lbAreaCerebro")
        self.gridLayout_3.addWidget(self.lbAreaCerebro, 4, 0, 1, 1)
        self.lbNumeroSesion = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbNumeroSesion.setObjectName("lbNumeroSesion")
        self.gridLayout_3.addWidget(self.lbNumeroSesion, 0, 0, 1, 1)
        self.lbFuncionCognitiva = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbFuncionCognitiva.setObjectName("lbFuncionCognitiva")
        self.gridLayout_3.addWidget(self.lbFuncionCognitiva, 1, 0, 1, 1)
        self.lbTipoOnda = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbTipoOnda.setObjectName("lbTipoOnda")
        self.gridLayout_3.addWidget(self.lbTipoOnda, 2, 0, 1, 1)
        self.lbEjercicio = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbEjercicio.setObjectName("lbEjercicio")
        self.gridLayout_3.addWidget(self.lbEjercicio, 8, 0, 1, 1)
        self.lbDuracion = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbDuracion.setObjectName("lbDuracion")
        self.gridLayout_3.addWidget(self.lbDuracion, 7, 0, 1, 1)
        self.lbNumeroAciertos = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbNumeroAciertos.setObjectName("lbNumeroAciertos")
        self.gridLayout_3.addWidget(self.lbNumeroAciertos, 9, 0, 1, 1)
        self.lbDivision = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lbDivision.setObjectName("lbDivision")
        self.gridLayout_3.addWidget(self.lbDivision, 3, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(220, 420, 291, 111))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbNombreTera = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.lbNombreTera.setObjectName("lbNombreTera")
        self.gridLayout_4.addWidget(self.lbNombreTera, 0, 0, 1, 1)
        self.contactoTera = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.contactoTera.setObjectName("contactoTera")
        self.gridLayout_4.addWidget(self.contactoTera, 1, 0, 1, 1)
        self.estatusTera = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.estatusTera.setObjectName("estatusTera")
        self.gridLayout_4.addWidget(self.estatusTera, 2, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(40, 420, 181, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 0, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 1, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 2, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(40, 580, 181, 131))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 2, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 1, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 3, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 6, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(220, 580, 291, 131))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbLocalida = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.lbLocalida.setObjectName("lbLocalida")
        self.gridLayout_7.addWidget(self.lbLocalida, 2, 0, 1, 1)
        self.lbTutor = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.lbTutor.setObjectName("lbTutor")
        self.gridLayout_7.addWidget(self.lbTutor, 3, 0, 1, 1)
        self.nombrePaciente = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.nombrePaciente.setObjectName("nombrePaciente")
        self.gridLayout_7.addWidget(self.nombrePaciente, 0, 0, 1, 1)
        self.lbContacto = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.lbContacto.setObjectName("lbContacto")
        self.gridLayout_7.addWidget(self.lbContacto, 4, 0, 1, 1)
        self.lbEdad = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.lbEdad.setObjectName("lbEdad")
        self.gridLayout_7.addWidget(self.lbEdad, 1, 0, 1, 1)
        self.lb1_6 = QtWidgets.QLabel(self.frame_2)
        self.lb1_6.setGeometry(QtCore.QRect(40, 730, 161, 21))
        self.lb1_6.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_6.setObjectName("lb1_6")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(10, 730, 31, 21))
        self.label_38.setAutoFillBackground(False)
        self.label_38.setStyleSheet("image: url(:/newPrefix/archivo.png);")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.lbObservaciones = QtWidgets.QLabel(self.frame_2)
        self.lbObservaciones.setGeometry(QtCore.QRect(40, 760, 481, 91))
        self.lbObservaciones.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.lbObservaciones.setObjectName("lbObservaciones")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(-10, 80, 571, 3))
        self.label_2.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lb1_2.setText(_translate("Dialog", "Reporte Terapeutico"))
        self.label_3.setText(_translate("Dialog", "CogniDron-EEG"))
        self.label_18.setText(_translate("Dialog", "12 de octubre del 2021"))
        self.lb1_3.setText(_translate("Dialog", "Datos de la sesión:"))
        self.lb1_4.setText(_translate("Dialog", "Datos del Terapeuta:"))
        self.lb1_5.setText(_translate("Dialog", "Datos del paciente:"))
        self.label_11.setText(_translate("Dialog", "Área del cerebro:"))
        self.label_14.setText(_translate("Dialog", "Numero de la sesión:"))
        self.label_15.setText(_translate("Dialog", "Funcuión cognitiva trabajada:"))
        self.label_17.setText(_translate("Dialog", "Tipo de ondas cerebrales:"))
        self.label_19.setText(_translate("Dialog", "Nombre de ejercicio:"))
        self.label_20.setText(_translate("Dialog", "Duración de la sesión:"))
        self.label_21.setText(_translate("Dialog", "Número de acieros:"))
        self.label_16.setText(_translate("Dialog", "Division Theta/Beta:"))
        self.lbAreaCerebro.setText(_translate("Dialog", "Prefrontal central"))
        self.lbNumeroSesion.setText(_translate("Dialog", "001"))
        self.lbFuncionCognitiva.setText(_translate("Dialog", "Atencion Focalizada"))
        self.lbTipoOnda.setText(_translate("Dialog", "Theta/Beta"))
        self.lbEjercicio.setText(_translate("Dialog", "Elevar Dron"))
        self.lbDuracion.setText(_translate("Dialog", "15 minutos"))
        self.lbNumeroAciertos.setText(_translate("Dialog", "4 de 10"))
        self.lbDivision.setText(_translate("Dialog", "3.1234"))
        self.lbNombreTera.setText(_translate("Dialog", "Raul Ramirez"))
        self.contactoTera.setText(_translate("Dialog", "3751009821"))
        self.estatusTera.setText(_translate("Dialog", "Activo"))
        self.label_47.setText(_translate("Dialog", "Nombre:"))
        self.label_49.setText(_translate("Dialog", "Contacto:"))
        self.label_46.setText(_translate("Dialog", "Estatus:"))
        self.label_53.setText(_translate("Dialog", "Localidad:"))
        self.label_51.setText(_translate("Dialog", "Nombre:"))
        self.label_52.setText(_translate("Dialog", "Edad:"))
        self.label_50.setText(_translate("Dialog", "Tutor:"))
        self.label_55.setText(_translate("Dialog", "Contacto:"))
        self.lbLocalida.setText(_translate("Dialog", "Angelica Montes"))
        self.lbTutor.setText(_translate("Dialog", "Ameca"))
        self.nombrePaciente.setText(_translate("Dialog", "Dniel Ruvalcaba"))
        self.lbContacto.setText(_translate("Dialog", "3751016714"))
        self.lbEdad.setText(_translate("Dialog", "12 años"))
        self.lb1_6.setText(_translate("Dialog", "Observaciones"))
        self.lbObservaciones.setText(_translate("Dialog", "El paciente mostro una mejora de atencion significativa en los primero 2 minutos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

