# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporteEspecifico.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images

class Ui_ReporteEspecifico(object):
    def setupUi(self, ReporteEspecifico):
        ReporteEspecifico.setObjectName("ReporteEspecifico")
        ReporteEspecifico.resize(1008, 802)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/idea-genial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReporteEspecifico.setWindowIcon(icon)
        self.frame_3 = QtWidgets.QFrame(ReporteEspecifico)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1011, 81))
        self.frame_3.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 631, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_11.setObjectName("label_11")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(930, 10, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("image: url(:/newPrefix/reporte.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.frame_4 = QtWidgets.QFrame(ReporteEspecifico)
        self.frame_4.setGeometry(QtCore.QRect(0, 80, 1021, 6))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.lbPorcentajeLogrado = QtWidgets.QLabel(ReporteEspecifico)
        self.lbPorcentajeLogrado.setGeometry(QtCore.QRect(480, 740, 171, 31))
        self.lbPorcentajeLogrado.setStyleSheet("font: 87 8pt \"Arial Black\";")
        self.lbPorcentajeLogrado.setObjectName("lbPorcentajeLogrado")
        self.label_70 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_70.setGeometry(QtCore.QRect(40, 650, 131, 21))
        self.label_70.setObjectName("label_70")
        self.label_63 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_63.setGeometry(QtCore.QRect(40, 242, 119, 20))
        self.label_63.setObjectName("label_63")
        self.line_31 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_31.setGeometry(QtCore.QRect(340, 462, 311, 2))
        self.line_31.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_31.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.label_27 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_27.setGeometry(QtCore.QRect(37, 442, 141, 23))
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_31.setGeometry(QtCore.QRect(340, 680, 171, 23))
        self.label_31.setObjectName("label_31")
        self.line_43 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_43.setGeometry(QtCore.QRect(30, 672, 621, 2))
        self.line_43.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_43.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.label_35 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_35.setGeometry(QtCore.QRect(37, 560, 201, 22))
        self.label_35.setObjectName("label_35")
        self.label_19 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_19.setGeometry(QtCore.QRect(330, 172, 31, 21))
        self.label_19.setAutoFillBackground(False)
        self.label_19.setStyleSheet("image: url(:/newPrefix/terapeuta.png);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.line_44 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_44.setGeometry(QtCore.QRect(650, 612, 2, 121))
        self.line_44.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_44.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_44.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.label_39 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_39.setGeometry(QtCore.QRect(670, 372, 31, 21))
        self.label_39.setAutoFillBackground(False)
        self.label_39.setStyleSheet("image: url(:/newPrefix/archivo.png);")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_71 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_71.setGeometry(QtCore.QRect(40, 472, 131, 20))
        self.label_71.setObjectName("label_71")
        self.line_35 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_35.setGeometry(QtCore.QRect(173, 402, 2, 211))
        self.line_35.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_35.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.label_33 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_33.setGeometry(QtCore.QRect(340, 710, 171, 23))
        self.label_33.setObjectName("label_33")
        self.line_21 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_21.setGeometry(QtCore.QRect(30, 402, 2, 211))
        self.line_21.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_21.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_18 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_18.setGeometry(QtCore.QRect(420, 202, 2, 151))
        self.line_18.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_18.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.label_74 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_74.setGeometry(QtCore.QRect(40, 414, 111, 20))
        self.label_74.setObjectName("label_74")
        self.line_4 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_4.setGeometry(QtCore.QRect(100, 202, 2, 151))
        self.line_4.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_4.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.lbElectrodos = QtWidgets.QLabel(ReporteEspecifico)
        self.lbElectrodos.setGeometry(QtCore.QRect(180, 588, 451, 22))
        self.lbElectrodos.setObjectName("lbElectrodos")
        self.line_29 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_29.setGeometry(QtCore.QRect(340, 552, 311, 2))
        self.line_29.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_29.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.lbcontactoTera = QtWidgets.QLabel(ReporteEspecifico)
        self.lbcontactoTera.setGeometry(QtCore.QRect(430, 320, 189, 39))
        self.lbcontactoTera.setObjectName("lbcontactoTera")
        self.lb1_8 = QtWidgets.QLabel(ReporteEspecifico)
        self.lb1_8.setGeometry(QtCore.QRect(360, 172, 161, 21))
        self.lb1_8.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_8.setObjectName("lb1_8")
        self.line_3 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_3.setGeometry(QtCore.QRect(30, 202, 2, 151))
        self.line_3.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_3.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lb1_9 = QtWidgets.QLabel(ReporteEspecifico)
        self.lb1_9.setGeometry(QtCore.QRect(40, 372, 161, 21))
        self.lb1_9.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_9.setObjectName("lb1_9")
        self.lbIdentificador = QtWidgets.QLabel(ReporteEspecifico)
        self.lbIdentificador.setGeometry(QtCore.QRect(230, 90, 341, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbIdentificador.setFont(font)
        self.lbIdentificador.setObjectName("lbIdentificador")
        self.lbNombreTera = QtWidgets.QLabel(ReporteEspecifico)
        self.lbNombreTera.setGeometry(QtCore.QRect(430, 203, 211, 38))
        self.lbNombreTera.setObjectName("lbNombreTera")
        self.line_50 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_50.setGeometry(QtCore.QRect(173, 612, 2, 121))
        self.line_50.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_50.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_50.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.lbMoyorUmbral = QtWidgets.QLabel(ReporteEspecifico)
        self.lbMoyorUmbral.setGeometry(QtCore.QRect(480, 670, 171, 41))
        self.lbMoyorUmbral.setObjectName("lbMoyorUmbral")
        self.label_72 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_72.setGeometry(QtCore.QRect(40, 532, 119, 20))
        self.label_72.setObjectName("label_72")
        self.lbEdadTera = QtWidgets.QLabel(ReporteEspecifico)
        self.lbEdadTera.setGeometry(QtCore.QRect(430, 245, 161, 20))
        self.lbEdadTera.setObjectName("lbEdadTera")
        self.label_61 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_61.setGeometry(QtCore.QRect(40, 301, 119, 20))
        self.label_61.setObjectName("label_61")
        self.line_27 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_27.setGeometry(QtCore.QRect(30, 612, 621, 2))
        self.line_27.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_27.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.label_62 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_62.setGeometry(QtCore.QRect(40, 270, 119, 21))
        self.label_62.setObjectName("label_62")
        self.lbLocalidaPaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbLocalidaPaciente.setGeometry(QtCore.QRect(110, 270, 221, 21))
        self.lbLocalidaPaciente.setObjectName("lbLocalidaPaciente")
        self.lbEntorno = QtWidgets.QLabel(ReporteEspecifico)
        self.lbEntorno.setGeometry(QtCore.QRect(180, 462, 189, 38))
        self.lbEntorno.setObjectName("lbEntorno")
        self.lbTutorPaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTutorPaciente.setGeometry(QtCore.QRect(110, 299, 221, 20))
        self.lbTutorPaciente.setObjectName("lbTutorPaciente")
        self.line_13 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_13.setGeometry(QtCore.QRect(350, 202, 2, 151))
        self.line_13.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_13.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.lbTipoEjericio = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTipoEjericio.setGeometry(QtCore.QRect(180, 650, 221, 21))
        self.lbTipoEjericio.setObjectName("lbTipoEjericio")
        self.line_9 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_9.setGeometry(QtCore.QRect(30, 322, 301, 2))
        self.line_9.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_9.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lbPromedioUmbral = QtWidgets.QLabel(ReporteEspecifico)
        self.lbPromedioUmbral.setGeometry(QtCore.QRect(480, 700, 171, 41))
        self.lbPromedioUmbral.setObjectName("lbPromedioUmbral")
        self.label_68 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_68.setGeometry(QtCore.QRect(360, 303, 119, 20))
        self.label_68.setObjectName("label_68")
        self.label_67 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_67.setGeometry(QtCore.QRect(360, 212, 119, 20))
        self.label_67.setObjectName("label_67")
        self.lbDuracion = QtWidgets.QLabel(ReporteEspecifico)
        self.lbDuracion.setGeometry(QtCore.QRect(180, 680, 171, 22))
        self.lbDuracion.setObjectName("lbDuracion")
        self.label = QtWidgets.QLabel(ReporteEspecifico)
        self.label.setGeometry(QtCore.QRect(20, 91, 251, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_45 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_45.setGeometry(QtCore.QRect(30, 732, 621, 2))
        self.line_45.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_45.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_45.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.line_14 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_14.setGeometry(QtCore.QRect(350, 262, 301, 2))
        self.line_14.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_14.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_32 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_32.setGeometry(QtCore.QRect(340, 522, 311, 2))
        self.line_32.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_32.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.lbNombrePaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbNombrePaciente.setGeometry(QtCore.QRect(110, 212, 221, 20))
        self.lbNombrePaciente.setObjectName("lbNombrePaciente")
        self.line = QtWidgets.QFrame(ReporteEspecifico)
        self.line.setGeometry(QtCore.QRect(30, 352, 301, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_64 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_64.setGeometry(QtCore.QRect(40, 213, 119, 20))
        self.label_64.setObjectName("label_64")
        self.lb1_11 = QtWidgets.QLabel(ReporteEspecifico)
        self.lb1_11.setGeometry(QtCore.QRect(700, 372, 201, 21))
        self.lb1_11.setStyleSheet("font: 10pt \"Times New Roman\";")
        self.lb1_11.setObjectName("lb1_11")
        self.lbFecha = QtWidgets.QLabel(ReporteEspecifico)
        self.lbFecha.setGeometry(QtCore.QRect(180, 442, 151, 22))
        self.lbFecha.setObjectName("lbFecha")
        self.btnAbrirGrafico = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnAbrirGrafico.setGeometry(QtCore.QRect(680, 252, 130, 40))
        self.btnAbrirGrafico.setObjectName("btnAbrirGrafico")
        self.lb1_7 = QtWidgets.QLabel(ReporteEspecifico)
        self.lb1_7.setGeometry(QtCore.QRect(40, 172, 161, 21))
        self.lb1_7.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lb1_7.setObjectName("lb1_7")
        self.lbMenorUmbral = QtWidgets.QLabel(ReporteEspecifico)
        self.lbMenorUmbral.setGeometry(QtCore.QRect(480, 640, 171, 41))
        self.lbMenorUmbral.setObjectName("lbMenorUmbral")
        self.label_29 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_29.setGeometry(QtCore.QRect(340, 650, 171, 22))
        self.label_29.setObjectName("label_29")
        self.label_28 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_28.setGeometry(QtCore.QRect(40, 592, 131, 22))
        self.label_28.setObjectName("label_28")
        self.line_5 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_5.setGeometry(QtCore.QRect(330, 202, 2, 151))
        self.line_5.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_5.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_51 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_51.setGeometry(QtCore.QRect(30, 612, 2, 121))
        self.line_51.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_51.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_51.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_51.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_51.setObjectName("line_51")
        self.line_23 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_23.setGeometry(QtCore.QRect(30, 552, 311, 2))
        self.line_23.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_23.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.label_23 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_23.setGeometry(QtCore.QRect(40, 680, 141, 23))
        self.label_23.setObjectName("label_23")
        self.label_30 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_30.setGeometry(QtCore.QRect(40, 710, 141, 23))
        self.label_30.setObjectName("label_30")
        self.line_2 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_2.setGeometry(QtCore.QRect(30, 202, 301, 2))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_21 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_21.setGeometry(QtCore.QRect(40, 745, 121, 23))
        self.label_21.setObjectName("label_21")
        self.lbContactoPaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbContactoPaciente.setGeometry(QtCore.QRect(110, 331, 121, 20))
        self.lbContactoPaciente.setObjectName("lbContactoPaciente")
        self.line_20 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_20.setGeometry(QtCore.QRect(30, 432, 311, 2))
        self.line_20.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_20.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_19 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_19.setGeometry(QtCore.QRect(30, 462, 311, 2))
        self.line_19.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_19.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.tpObservaciones = QtWidgets.QPlainTextEdit(ReporteEspecifico)
        self.tpObservaciones.setEnabled(False)
        self.tpObservaciones.setGeometry(QtCore.QRect(680, 402, 311, 91))
        self.tpObservaciones.setStyleSheet("font: 8.5pt \"MS Shell Dlg 2\";")
        self.tpObservaciones.setObjectName("tpObservaciones")
        self.line_38 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_38.setGeometry(QtCore.QRect(30, 402, 621, 2))
        self.line_38.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_38.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_38.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.line_26 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_26.setGeometry(QtCore.QRect(330, 612, 2, 121))
        self.line_26.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_26.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_25 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_25.setGeometry(QtCore.QRect(30, 492, 311, 2))
        self.line_25.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_25.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.label_65 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_65.setGeometry(QtCore.QRect(360, 273, 119, 21))
        self.label_65.setObjectName("label_65")
        self.lbPromedioPotencia = QtWidgets.QLabel(ReporteEspecifico)
        self.lbPromedioPotencia.setGeometry(QtCore.QRect(180, 710, 171, 22))
        self.lbPromedioPotencia.setObjectName("lbPromedioPotencia")
        self.line_6 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_6.setGeometry(QtCore.QRect(30, 232, 301, 2))
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_6.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_32 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_32.setGeometry(QtCore.QRect(340, 745, 141, 23))
        self.label_32.setObjectName("label_32")
        self.lbBandaTrabajada = QtWidgets.QLabel(ReporteEspecifico)
        self.lbBandaTrabajada.setGeometry(QtCore.QRect(180, 745, 151, 22))
        self.lbBandaTrabajada.setObjectName("lbBandaTrabajada")
        self.groupBox = QtWidgets.QGroupBox(ReporteEspecifico)
        self.groupBox.setGeometry(QtCore.QRect(680, 302, 301, 51))
        self.groupBox.setObjectName("groupBox")
        self.rbGrafLIneal_2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbGrafLIneal_2.setGeometry(QtCore.QRect(20, 20, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbGrafLIneal_2.setFont(font)
        self.rbGrafLIneal_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbGrafLIneal_2.setChecked(True)
        self.rbGrafLIneal_2.setObjectName("rbGrafLIneal_2")
        self.rbGrafBarras_2 = QtWidgets.QRadioButton(self.groupBox)
        self.rbGrafBarras_2.setGeometry(QtCore.QRect(180, 20, 111, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.rbGrafBarras_2.setFont(font)
        self.rbGrafBarras_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.rbGrafBarras_2.setChecked(False)
        self.rbGrafBarras_2.setObjectName("rbGrafBarras_2")
        self.lbEdadPaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbEdadPaciente.setGeometry(QtCore.QRect(110, 242, 161, 20))
        self.lbEdadPaciente.setObjectName("lbEdadPaciente")
        self.line_47 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_47.setGeometry(QtCore.QRect(30, 612, 301, 2))
        self.line_47.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_47.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.label_66 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_66.setGeometry(QtCore.QRect(360, 243, 119, 20))
        self.label_66.setObjectName("label_66")
        self.line_48 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_48.setGeometry(QtCore.QRect(30, 702, 621, 2))
        self.line_48.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_48.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.lbNombreEjercicio = QtWidgets.QLabel(ReporteEspecifico)
        self.lbNombreEjercicio.setGeometry(QtCore.QRect(180, 521, 211, 38))
        self.lbNombreEjercicio.setObjectName("lbNombreEjercicio")
        self.line_34 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_34.setGeometry(QtCore.QRect(650, 402, 2, 211))
        self.line_34.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_34.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_12 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_12.setGeometry(QtCore.QRect(350, 292, 301, 2))
        self.line_12.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_12.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.lbestatusTera = QtWidgets.QLabel(ReporteEspecifico)
        self.lbestatusTera.setGeometry(QtCore.QRect(430, 292, 189, 38))
        self.lbestatusTera.setObjectName("lbestatusTera")
        self.line_11 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_11.setGeometry(QtCore.QRect(350, 322, 301, 2))
        self.line_11.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_11.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_37 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_37.setGeometry(QtCore.QRect(470, 612, 2, 121))
        self.line_37.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_37.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.btnEmviarReporte = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnEmviarReporte.setGeometry(QtCore.QRect(850, 252, 130, 40))
        self.btnEmviarReporte.setObjectName("btnEmviarReporte")
        self.line_22 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_22.setGeometry(QtCore.QRect(340, 432, 311, 2))
        self.line_22.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_22.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.btnReportes = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnReportes.setGeometry(QtCore.QRect(680, 202, 130, 40))
        self.btnReportes.setObjectName("btnReportes")
        self.btnVideo = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnVideo.setEnabled(False)
        self.btnVideo.setGeometry(QtCore.QRect(850, 202, 130, 40))
        self.btnVideo.setObjectName("btnVideo")
        self.lbRobot = QtWidgets.QLabel(ReporteEspecifico)
        self.lbRobot.setGeometry(QtCore.QRect(180, 492, 189, 39))
        self.lbRobot.setObjectName("lbRobot")
        self.line_7 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_7.setGeometry(QtCore.QRect(30, 262, 301, 2))
        self.line_7.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_7.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_18 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_18.setGeometry(QtCore.QRect(10, 172, 31, 21))
        self.label_18.setAutoFillBackground(False)
        self.label_18.setStyleSheet("image: url(:/newPrefix/paciente.png);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_73 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_73.setGeometry(QtCore.QRect(40, 504, 61, 20))
        self.label_73.setObjectName("label_73")
        self.line_24 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_24.setGeometry(QtCore.QRect(30, 522, 311, 2))
        self.line_24.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_24.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.lbLocalidadTera = QtWidgets.QLabel(ReporteEspecifico)
        self.lbLocalidadTera.setGeometry(QtCore.QRect(430, 272, 221, 21))
        self.lbLocalidadTera.setObjectName("lbLocalidadTera")
        self.line_30 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_30.setGeometry(QtCore.QRect(340, 582, 311, 2))
        self.line_30.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_30.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_10 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_10.setGeometry(QtCore.QRect(350, 352, 301, 2))
        self.line_10.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_10.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_60 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_60.setGeometry(QtCore.QRect(40, 331, 61, 20))
        self.label_60.setObjectName("label_60")
        self.line_17 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_17.setGeometry(QtCore.QRect(650, 202, 2, 151))
        self.line_17.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_17.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_15 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_15.setGeometry(QtCore.QRect(350, 232, 301, 2))
        self.line_15.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_15.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_28 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_28.setGeometry(QtCore.QRect(30, 582, 311, 2))
        self.line_28.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_28.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.label_69 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_69.setGeometry(QtCore.QRect(360, 333, 61, 20))
        self.label_69.setObjectName("label_69")
        self.line_8 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_8.setGeometry(QtCore.QRect(30, 292, 301, 2))
        self.line_8.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_8.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_20 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_20.setGeometry(QtCore.QRect(10, 372, 31, 21))
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("image: url(:/newPrefix/reporte.png);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.line_16 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_16.setGeometry(QtCore.QRect(350, 202, 301, 2))
        self.line_16.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_16.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.lbTipoTerapia = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTipoTerapia.setGeometry(QtCore.QRect(180, 412, 141, 20))
        self.lbTipoTerapia.setObjectName("lbTipoTerapia")
        self.line_46 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_46.setGeometry(QtCore.QRect(30, 642, 621, 2))
        self.line_46.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_46.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_46.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.line_33 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_33.setGeometry(QtCore.QRect(340, 492, 311, 2))
        self.line_33.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_33.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.lbFuncionesCognitivas = QtWidgets.QLabel(ReporteEspecifico)
        self.lbFuncionesCognitivas.setGeometry(QtCore.QRect(180, 560, 461, 22))
        self.lbFuncionesCognitivas.setObjectName("lbFuncionesCognitivas")
        self.label_8 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_8.setGeometry(QtCore.QRect(0, 90, 1011, 721))
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.label_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.line_49 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_49.setGeometry(QtCore.QRect(30, 770, 621, 2))
        self.line_49.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_49.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_49.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.line_52 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_52.setGeometry(QtCore.QRect(650, 650, 2, 121))
        self.line_52.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_52.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_52.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_52.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_52.setObjectName("line_52")
        self.line_53 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_53.setGeometry(QtCore.QRect(470, 650, 2, 121))
        self.line_53.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_53.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_53.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_53.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_53.setObjectName("line_53")
        self.line_54 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_54.setGeometry(QtCore.QRect(330, 650, 2, 121))
        self.line_54.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_54.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_54.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_54.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_54.setObjectName("line_54")
        self.line_55 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_55.setGeometry(QtCore.QRect(173, 650, 2, 121))
        self.line_55.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_55.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_55.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.line_56 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_56.setGeometry(QtCore.QRect(1010, 640, 2, 121))
        self.line_56.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_56.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.line_57 = QtWidgets.QFrame(ReporteEspecifico)
        self.line_57.setGeometry(QtCore.QRect(30, 650, 2, 121))
        self.line_57.setMaximumSize(QtCore.QSize(2, 16777215))
        self.line_57.setStyleSheet("background-color: rgb(72, 72, 72);")
        self.line_57.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_57.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_57.setObjectName("line_57")
        self.lbnumUmbrales = QtWidgets.QLabel(ReporteEspecifico)
        self.lbnumUmbrales.setGeometry(QtCore.QRect(180, 620, 161, 21))
        self.lbnumUmbrales.setObjectName("lbnumUmbrales")
        self.label_34 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_34.setGeometry(QtCore.QRect(340, 620, 131, 22))
        self.label_34.setObjectName("label_34")
        self.label_75 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_75.setGeometry(QtCore.QRect(40, 617, 131, 21))
        self.label_75.setObjectName("label_75")
        self.lbPrimerUmbral = QtWidgets.QLabel(ReporteEspecifico)
        self.lbPrimerUmbral.setGeometry(QtCore.QRect(480, 610, 171, 41))
        self.lbPrimerUmbral.setObjectName("lbPrimerUmbral")
        self.label_8.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.lbPorcentajeLogrado.raise_()
        self.label_70.raise_()
        self.label_63.raise_()
        self.line_31.raise_()
        self.label_27.raise_()
        self.label_31.raise_()
        self.line_43.raise_()
        self.label_35.raise_()
        self.label_19.raise_()
        self.line_44.raise_()
        self.label_39.raise_()
        self.label_71.raise_()
        self.line_35.raise_()
        self.label_33.raise_()
        self.line_21.raise_()
        self.line_18.raise_()
        self.label_74.raise_()
        self.line_4.raise_()
        self.lbElectrodos.raise_()
        self.line_29.raise_()
        self.lbcontactoTera.raise_()
        self.lb1_8.raise_()
        self.line_3.raise_()
        self.lb1_9.raise_()
        self.lbIdentificador.raise_()
        self.lbNombreTera.raise_()
        self.line_50.raise_()
        self.lbMoyorUmbral.raise_()
        self.label_72.raise_()
        self.lbEdadTera.raise_()
        self.label_61.raise_()
        self.line_27.raise_()
        self.label_62.raise_()
        self.lbLocalidaPaciente.raise_()
        self.lbEntorno.raise_()
        self.lbTutorPaciente.raise_()
        self.line_13.raise_()
        self.lbTipoEjericio.raise_()
        self.line_9.raise_()
        self.lbPromedioUmbral.raise_()
        self.label_68.raise_()
        self.label_67.raise_()
        self.lbDuracion.raise_()
        self.label.raise_()
        self.line_45.raise_()
        self.line_14.raise_()
        self.line_32.raise_()
        self.lbNombrePaciente.raise_()
        self.line.raise_()
        self.label_64.raise_()
        self.lb1_11.raise_()
        self.lbFecha.raise_()
        self.btnAbrirGrafico.raise_()
        self.lb1_7.raise_()
        self.lbMenorUmbral.raise_()
        self.label_29.raise_()
        self.label_28.raise_()
        self.line_5.raise_()
        self.line_51.raise_()
        self.line_23.raise_()
        self.label_23.raise_()
        self.label_30.raise_()
        self.line_2.raise_()
        self.label_21.raise_()
        self.lbContactoPaciente.raise_()
        self.line_20.raise_()
        self.line_19.raise_()
        self.tpObservaciones.raise_()
        self.line_38.raise_()
        self.line_26.raise_()
        self.line_25.raise_()
        self.label_65.raise_()
        self.lbPromedioPotencia.raise_()
        self.line_6.raise_()
        self.label_32.raise_()
        self.lbBandaTrabajada.raise_()
        self.groupBox.raise_()
        self.lbEdadPaciente.raise_()
        self.line_47.raise_()
        self.label_66.raise_()
        self.line_48.raise_()
        self.lbNombreEjercicio.raise_()
        self.line_34.raise_()
        self.line_12.raise_()
        self.lbestatusTera.raise_()
        self.line_11.raise_()
        self.line_37.raise_()
        self.btnEmviarReporte.raise_()
        self.line_22.raise_()
        self.btnReportes.raise_()
        self.btnVideo.raise_()
        self.lbRobot.raise_()
        self.line_7.raise_()
        self.label_18.raise_()
        self.label_73.raise_()
        self.line_24.raise_()
        self.lbLocalidadTera.raise_()
        self.line_30.raise_()
        self.line_10.raise_()
        self.label_60.raise_()
        self.line_17.raise_()
        self.line_15.raise_()
        self.line_28.raise_()
        self.label_69.raise_()
        self.line_8.raise_()
        self.label_20.raise_()
        self.line_16.raise_()
        self.lbTipoTerapia.raise_()
        self.line_46.raise_()
        self.line_33.raise_()
        self.lbFuncionesCognitivas.raise_()
        self.line_49.raise_()
        self.line_52.raise_()
        self.line_53.raise_()
        self.line_54.raise_()
        self.line_55.raise_()
        self.line_56.raise_()
        self.line_57.raise_()
        self.lbnumUmbrales.raise_()
        self.label_34.raise_()
        self.label_75.raise_()
        self.lbPrimerUmbral.raise_()

        self.retranslateUi(ReporteEspecifico)
        QtCore.QMetaObject.connectSlotsByName(ReporteEspecifico)

    def retranslateUi(self, ReporteEspecifico):
        _translate = QtCore.QCoreApplication.translate
        ReporteEspecifico.setWindowTitle(_translate("ReporteEspecifico", "Reporte de terapia"))
        self.label_11.setText(_translate("ReporteEspecifico", "Reporte de una terapia de tipo neurofeedback"))
        self.lbPorcentajeLogrado.setText(_translate("ReporteEspecifico", "45.12 %"))
        self.label_70.setText(_translate("ReporteEspecifico", "Tipo de ejercicio:"))
        self.label_63.setText(_translate("ReporteEspecifico", "Edad:"))
        self.label_27.setText(_translate("ReporteEspecifico", "Fecha de terapia:"))
        self.label_31.setText(_translate("ReporteEspecifico", "Mayor umbral:"))
        self.label_35.setText(_translate("ReporteEspecifico", "Funciones cognitivas:"))
        self.label_71.setText(_translate("ReporteEspecifico", "Tipo de entorno:"))
        self.label_33.setText(_translate("ReporteEspecifico", "Promedio umbral:"))
        self.label_74.setText(_translate("ReporteEspecifico", "Tipo de terapia:"))
        self.lbElectrodos.setText(_translate("ReporteEspecifico", "F3, F4, F3, F4, F3, F4, F3, F4, F3, F4, F3, F4, F3, F4,"))
        self.lbcontactoTera.setText(_translate("ReporteEspecifico", "3751009821"))
        self.lb1_8.setText(_translate("ReporteEspecifico", "Datos del Terapeuta:"))
        self.lb1_9.setText(_translate("ReporteEspecifico", "Datos de la sesión:"))
        self.lbIdentificador.setText(_translate("ReporteEspecifico", "Numero"))
        self.lbNombreTera.setText(_translate("ReporteEspecifico", "Raul Ramirez"))
        self.lbMoyorUmbral.setText(_translate("ReporteEspecifico", "9 segundos"))
        self.label_72.setText(_translate("ReporteEspecifico", "Nombre de ejercicio:"))
        self.lbEdadTera.setText(_translate("ReporteEspecifico", "12 años"))
        self.label_61.setText(_translate("ReporteEspecifico", "Tutor:"))
        self.label_62.setText(_translate("ReporteEspecifico", "Localidad:"))
        self.lbLocalidaPaciente.setText(_translate("ReporteEspecifico", "Ameca"))
        self.lbEntorno.setText(_translate("ReporteEspecifico", "Entorno real"))
        self.lbTutorPaciente.setText(_translate("ReporteEspecifico", "Angelica Montes"))
        self.lbTipoEjericio.setText(_translate("ReporteEspecifico", "Inivitorio"))
        self.lbPromedioUmbral.setText(_translate("ReporteEspecifico", "6 segundos"))
        self.label_68.setText(_translate("ReporteEspecifico", "Estatus:"))
        self.label_67.setText(_translate("ReporteEspecifico", "Nombre:"))
        self.lbDuracion.setText(_translate("ReporteEspecifico", "15 minutos"))
        self.label.setText(_translate("ReporteEspecifico", "Numero de reporte:"))
        self.lbNombrePaciente.setText(_translate("ReporteEspecifico", "Daniel Ruvalcaba"))
        self.label_64.setText(_translate("ReporteEspecifico", "Nombre:"))
        self.lb1_11.setText(_translate("ReporteEspecifico", "Observaciones de la terapia"))
        self.lbFecha.setText(_translate("ReporteEspecifico", "17-01-2022"))
        self.btnAbrirGrafico.setText(_translate("ReporteEspecifico", "Graficos de sesiones"))
        self.lb1_7.setText(_translate("ReporteEspecifico", "Datos del paciente:"))
        self.lbMenorUmbral.setText(_translate("ReporteEspecifico", "3 segundos"))
        self.label_29.setText(_translate("ReporteEspecifico", "Menor umbral:"))
        self.label_28.setText(_translate("ReporteEspecifico", "Electrodos:"))
        self.label_23.setText(_translate("ReporteEspecifico", "Duración de la sesión:"))
        self.label_30.setText(_translate("ReporteEspecifico", "Promedio de potencia:"))
        self.label_21.setText(_translate("ReporteEspecifico", "Banda trabajada:"))
        self.lbContactoPaciente.setText(_translate("ReporteEspecifico", "3751016714"))
        self.tpObservaciones.setPlainText(_translate("ReporteEspecifico", "El niño tubo una biena concentracion....\n"
"\n"
"Execelnte trabajo!"))
        self.label_65.setText(_translate("ReporteEspecifico", "Localidad:"))
        self.lbPromedioPotencia.setText(_translate("ReporteEspecifico", "2.167"))
        self.label_32.setText(_translate("ReporteEspecifico", "Porcentaje logrado:"))
        self.lbBandaTrabajada.setText(_translate("ReporteEspecifico", "Theta/Beta completa"))
        self.groupBox.setTitle(_translate("ReporteEspecifico", "   Tipo de grafico :"))
        self.rbGrafLIneal_2.setText(_translate("ReporteEspecifico", "Lineal"))
        self.rbGrafBarras_2.setText(_translate("ReporteEspecifico", "Barras"))
        self.lbEdadPaciente.setText(_translate("ReporteEspecifico", "12 años"))
        self.label_66.setText(_translate("ReporteEspecifico", "Edad:"))
        self.lbNombreEjercicio.setText(_translate("ReporteEspecifico", "Elevar y decender dron"))
        self.lbestatusTera.setText(_translate("ReporteEspecifico", "Activo"))
        self.btnEmviarReporte.setText(_translate("ReporteEspecifico", "Imprimir reporte"))
        self.btnReportes.setText(_translate("ReporteEspecifico", "Reporte de potencias"))
        self.btnVideo.setText(_translate("ReporteEspecifico", "Visualizar ondas"))
        self.lbRobot.setText(_translate("ReporteEspecifico", "Dron Tello"))
        self.label_73.setText(_translate("ReporteEspecifico", "Robot :"))
        self.lbLocalidadTera.setText(_translate("ReporteEspecifico", "Ameca"))
        self.label_60.setText(_translate("ReporteEspecifico", "Contacto:"))
        self.label_69.setText(_translate("ReporteEspecifico", "Contacto:"))
        self.lbTipoTerapia.setText(_translate("ReporteEspecifico", "Neurofeedback"))
        self.lbFuncionesCognitivas.setText(_translate("ReporteEspecifico", "Antencion sostenida y atencion focalizada"))
        self.lbnumUmbrales.setText(_translate("ReporteEspecifico", "10"))
        self.label_34.setText(_translate("ReporteEspecifico", "Primel umbral:"))
        self.label_75.setText(_translate("ReporteEspecifico", "Num. Umbrales "))
        self.lbPrimerUmbral.setText(_translate("ReporteEspecifico", "2:20"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReporteEspecifico = QtWidgets.QDialog()
    ui = Ui_ReporteEspecifico()
    ui.setupUi(ReporteEspecifico)
    ReporteEspecifico.show()
    sys.exit(app.exec_())

