# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportesGenerales.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import  vistas.images
class Ui_Ui_ReportesGenerales_2(object):
    def setupUi(self, Ui_ReportesGenerales_2):
        Ui_ReportesGenerales_2.setObjectName("Ui_ReportesGenerales_2")
        Ui_ReportesGenerales_2.resize(759, 719)
        Ui_ReportesGenerales_2.setMinimumSize(QtCore.QSize(736, 717))
        Ui_ReportesGenerales_2.setMaximumSize(QtCore.QSize(759, 719))
        self.label_2 = QtWidgets.QLabel(Ui_ReportesGenerales_2)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 121, 51))
        self.label_2.setObjectName("label_2")
        self.cbfiltrar = QtWidgets.QComboBox(Ui_ReportesGenerales_2)
        self.cbfiltrar.setGeometry(QtCore.QRect(20, 140, 131, 22))
        self.cbfiltrar.setObjectName("cbfiltrar")
        self.cbfiltrar.addItem("")
        self.cbfiltrar.addItem("")
        self.label_3 = QtWidgets.QLabel(Ui_ReportesGenerales_2)
        self.label_3.setGeometry(QtCore.QRect(300, 140, 41, 16))
        self.label_3.setObjectName("label_3")
        self.btnConsultar = QtWidgets.QPushButton(Ui_ReportesGenerales_2)
        self.btnConsultar.setGeometry(QtCore.QRect(610, 140, 93, 28))
        self.btnConsultar.setObjectName("btnConsultar")
        self.tabla_pacientes = QtWidgets.QTableWidget(Ui_ReportesGenerales_2)
        self.tabla_pacientes.setGeometry(QtCore.QRect(10, 200, 731, 471))
        self.tabla_pacientes.setMinimumSize(QtCore.QSize(701, 471))
        self.tabla_pacientes.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabla_pacientes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tabla_pacientes.setDragEnabled(False)
        self.tabla_pacientes.setRowCount(0)
        self.tabla_pacientes.setColumnCount(6)
        self.tabla_pacientes.setObjectName("tabla_pacientes")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabla_pacientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 255, 127))
        self.tabla_pacientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 248, 53))
        self.tabla_pacientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 170, 127))
        self.tabla_pacientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 170, 0))
        self.tabla_pacientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(85, 170, 255))
        self.tabla_pacientes.setHorizontalHeaderItem(5, item)
        self.btnBuscarbaciente = QtWidgets.QPushButton(Ui_ReportesGenerales_2)
        self.btnBuscarbaciente.setGeometry(QtCore.QRect(160, 140, 31, 28))
        self.btnBuscarbaciente.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/lupa.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBuscarbaciente.setIcon(icon)
        self.btnBuscarbaciente.setObjectName("btnBuscarbaciente")
        self.dateEdit = QtWidgets.QDateEdit(Ui_ReportesGenerales_2)
        self.dateEdit.setGeometry(QtCore.QRect(350, 140, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.btnBuscarFecha = QtWidgets.QPushButton(Ui_ReportesGenerales_2)
        self.btnBuscarFecha.setGeometry(QtCore.QRect(470, 140, 31, 28))
        self.btnBuscarFecha.setText("")
        self.btnBuscarFecha.setIcon(icon)
        self.btnBuscarFecha.setObjectName("btnBuscarFecha")
        self.frame_3 = QtWidgets.QFrame(Ui_ReportesGenerales_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 771, 81))
        self.frame_3.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_11.setObjectName("label_11")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(680, 10, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("image: url(:/newPrefix/reporte.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.frame_4 = QtWidgets.QFrame(Ui_ReportesGenerales_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 80, 761, 8))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_14 = QtWidgets.QLabel(Ui_ReportesGenerales_2)
        self.label_14.setGeometry(QtCore.QRect(0, 70, 801, 651))
        self.label_14.setMinimumSize(QtCore.QSize(10, 10))
        self.label_14.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.label_14.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_14.raise_()
        self.label_2.raise_()
        self.cbfiltrar.raise_()
        self.label_3.raise_()
        self.btnConsultar.raise_()
        self.tabla_pacientes.raise_()
        self.btnBuscarbaciente.raise_()
        self.dateEdit.raise_()
        self.btnBuscarFecha.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()

        self.retranslateUi(Ui_ReportesGenerales_2)
        QtCore.QMetaObject.connectSlotsByName(Ui_ReportesGenerales_2)

    def retranslateUi(self, Ui_ReportesGenerales_2):
        _translate = QtCore.QCoreApplication.translate
        Ui_ReportesGenerales_2.setWindowTitle(_translate("Ui_ReportesGenerales_2", "Reportes Generales"))
        self.label_2.setText(_translate("Ui_ReportesGenerales_2", "Nombre del paciente"))
        self.cbfiltrar.setItemText(0, _translate("Ui_ReportesGenerales_2", "Paciente"))
        self.cbfiltrar.setItemText(1, _translate("Ui_ReportesGenerales_2", "Terapeuta"))
        self.label_3.setText(_translate("Ui_ReportesGenerales_2", "Fecha:"))
        self.btnConsultar.setText(_translate("Ui_ReportesGenerales_2", "Consultar"))
        item = self.tabla_pacientes.horizontalHeaderItem(0)
        item.setText(_translate("Ui_ReportesGenerales_2", "Identificador"))
        item = self.tabla_pacientes.horizontalHeaderItem(1)
        item.setText(_translate("Ui_ReportesGenerales_2", "Fecha"))
        item = self.tabla_pacientes.horizontalHeaderItem(2)
        item.setText(_translate("Ui_ReportesGenerales_2", "Ejercicio"))
        item = self.tabla_pacientes.horizontalHeaderItem(3)
        item.setText(_translate("Ui_ReportesGenerales_2", "Duración"))
        item = self.tabla_pacientes.horizontalHeaderItem(4)
        item.setText(_translate("Ui_ReportesGenerales_2", "Paciente"))
        item = self.tabla_pacientes.horizontalHeaderItem(5)
        item.setText(_translate("Ui_ReportesGenerales_2", "Terapeuta"))
        self.label_11.setText(_translate("Ui_ReportesGenerales_2", "Reportes Generales"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_ReportesGenerales_2 = QtWidgets.QDialog()
    ui = Ui_Ui_ReportesGenerales_2()
    ui.setupUi(Ui_ReportesGenerales_2)
    Ui_ReportesGenerales_2.show()
    sys.exit(app.exec_())

