# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reporteEspecifico.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images

class Ui_ReporteEspecifico(object):
    def setupUi(self, ReporteEspecifico):
        ReporteEspecifico.setObjectName("ReporteEspecifico")
        ReporteEspecifico.resize(599, 718)
        self.label = QtWidgets.QLabel(ReporteEspecifico)
        self.label.setGeometry(QtCore.QRect(20, 90, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label1 = QtWidgets.QLabel(ReporteEspecifico)
        self.label1.setGeometry(QtCore.QRect(30, 340, 111, 16))
        self.label1.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label1.setObjectName("label1")
        self.label_2 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_2.setGeometry(QtCore.QRect(30, 310, 51, 16))
        self.label_2.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_3.setGeometry(QtCore.QRect(30, 400, 91, 16))
        self.label_3.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_3.setObjectName("label_3")
        self.lbTipoOnda = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTipoOnda.setGeometry(QtCore.QRect(130, 400, 101, 20))
        self.lbTipoOnda.setObjectName("lbTipoOnda")
        self.label_4 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_4.setGeometry(QtCore.QRect(30, 460, 61, 16))
        self.label_4.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_4.setObjectName("label_4")
        self.btnVideo = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnVideo.setGeometry(QtCore.QRect(40, 520, 111, 41))
        self.btnVideo.setObjectName("btnVideo")
        self.btnReportes = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnReportes.setGeometry(QtCore.QRect(170, 520, 121, 41))
        self.btnReportes.setObjectName("btnReportes")
        self.btnEmviarReporte = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnEmviarReporte.setGeometry(QtCore.QRect(320, 520, 111, 41))
        self.btnEmviarReporte.setObjectName("btnEmviarReporte")
        self.label_6 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 71, 16))
        self.label_6.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_9.setGeometry(QtCore.QRect(30, 220, 51, 16))
        self.label_9.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_9.setObjectName("label_9")
        self.lbDuracion = QtWidgets.QLabel(ReporteEspecifico)
        self.lbDuracion.setGeometry(QtCore.QRect(90, 460, 151, 16))
        self.lbDuracion.setObjectName("lbDuracion")
        self.lbTerapeuta = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTerapeuta.setGeometry(QtCore.QRect(110, 190, 151, 16))
        self.lbTerapeuta.setObjectName("lbTerapeuta")
        self.lbTutor = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTutor.setGeometry(QtCore.QRect(80, 220, 151, 16))
        self.lbTutor.setObjectName("lbTutor")
        self.label_10 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_10.setGeometry(QtCore.QRect(30, 250, 61, 16))
        self.label_10.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_10.setObjectName("label_10")
        self.lbPaciente = QtWidgets.QLabel(ReporteEspecifico)
        self.lbPaciente.setGeometry(QtCore.QRect(100, 250, 151, 16))
        self.lbPaciente.setObjectName("lbPaciente")
        self.lbComentarios = QtWidgets.QLabel(ReporteEspecifico)
        self.lbComentarios.setGeometry(QtCore.QRect(20, 580, 551, 121))
        self.lbComentarios.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.lbComentarios.setStyleSheet("background-color: rgb(252, 255, 185);")
        self.lbComentarios.setText("")
        self.lbComentarios.setObjectName("lbComentarios")
        self.lbTipo = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTipo.setGeometry(QtCore.QRect(140, 340, 91, 16))
        self.lbTipo.setObjectName("lbTipo")
        self.lbFecha = QtWidgets.QLabel(ReporteEspecifico)
        self.lbFecha.setGeometry(QtCore.QRect(90, 310, 151, 16))
        self.lbFecha.setObjectName("lbFecha")
        self.lbIdentificador = QtWidgets.QLabel(ReporteEspecifico)
        self.lbIdentificador.setGeometry(QtCore.QRect(110, 90, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbIdentificador.setFont(font)
        self.lbIdentificador.setObjectName("lbIdentificador")
        self.label_5 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_5.setGeometry(QtCore.QRect(30, 430, 101, 16))
        self.label_5.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_5.setObjectName("label_5")
        self.lbMetaAlcanza = QtWidgets.QLabel(ReporteEspecifico)
        self.lbMetaAlcanza.setGeometry(QtCore.QRect(140, 430, 21, 20))
        self.lbMetaAlcanza.setObjectName("lbMetaAlcanza")
        self.lbEjercicio_3 = QtWidgets.QLabel(ReporteEspecifico)
        self.lbEjercicio_3.setGeometry(QtCore.QRect(160, 430, 21, 20))
        self.lbEjercicio_3.setObjectName("lbEjercicio_3")
        self.lbMetaPropuesta = QtWidgets.QLabel(ReporteEspecifico)
        self.lbMetaPropuesta.setGeometry(QtCore.QRect(190, 430, 21, 20))
        self.lbMetaPropuesta.setObjectName("lbMetaPropuesta")
        self.label_7 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_7.setGeometry(QtCore.QRect(330, 160, 251, 281))
        self.label_7.setStyleSheet("image: url(:/newPrefix/EjerElevar.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.btnAbrirGrafico = QtWidgets.QPushButton(ReporteEspecifico)
        self.btnAbrirGrafico.setGeometry(QtCore.QRect(460, 520, 111, 41))
        self.btnAbrirGrafico.setObjectName("btnAbrirGrafico")
        self.label_8 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_8.setGeometry(QtCore.QRect(0, 80, 600, 641))
        self.label_8.setMinimumSize(QtCore.QSize(600, 600))
        self.label_8.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.frame_3 = QtWidgets.QFrame(ReporteEspecifico)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 601, 81))
        self.frame_3.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_11.setObjectName("label_11")
        self.label_24 = QtWidgets.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(520, 10, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("image: url(:/newPrefix/reporte.png);")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.frame_4 = QtWidgets.QFrame(ReporteEspecifico)
        self.frame_4.setGeometry(QtCore.QRect(0, 80, 601, 8))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_12 = QtWidgets.QLabel(ReporteEspecifico)
        self.label_12.setGeometry(QtCore.QRect(30, 280, 61, 16))
        self.label_12.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label_12.setObjectName("label_12")
        self.lbFecha_2 = QtWidgets.QLabel(ReporteEspecifico)
        self.lbFecha_2.setGeometry(QtCore.QRect(80, 280, 151, 16))
        self.lbFecha_2.setObjectName("lbFecha_2")
        self.lbTipo_2 = QtWidgets.QLabel(ReporteEspecifico)
        self.lbTipo_2.setGeometry(QtCore.QRect(170, 370, 161, 16))
        self.lbTipo_2.setObjectName("lbTipo_2")
        self.label1_2 = QtWidgets.QLabel(ReporteEspecifico)
        self.label1_2.setGeometry(QtCore.QRect(30, 370, 141, 16))
        self.label1_2.setStyleSheet("font: 87 8pt \"Segoe UI Black\";")
        self.label1_2.setObjectName("label1_2")
        self.groupBox = QtWidgets.QGroupBox(ReporteEspecifico)
        self.groupBox.setGeometry(QtCore.QRect(460, 440, 111, 71))
        self.groupBox.setObjectName("groupBox")
        self.rbGrafLIneal = QtWidgets.QRadioButton(self.groupBox)
        self.rbGrafLIneal.setGeometry(QtCore.QRect(10, 20, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbGrafLIneal.setFont(font)
        self.rbGrafLIneal.setChecked(True)
        self.rbGrafLIneal.setObjectName("rbGrafLIneal")
        self.rbGrafBarras = QtWidgets.QRadioButton(self.groupBox)
        self.rbGrafBarras.setGeometry(QtCore.QRect(10, 50, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbGrafBarras.setFont(font)
        self.rbGrafBarras.setChecked(False)
        self.rbGrafBarras.setObjectName("rbGrafBarras")
        self.label_8.raise_()
        self.label.raise_()
        self.label1.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lbTipoOnda.raise_()
        self.label_4.raise_()
        self.btnVideo.raise_()
        self.btnReportes.raise_()
        self.btnEmviarReporte.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.lbDuracion.raise_()
        self.lbTerapeuta.raise_()
        self.lbTutor.raise_()
        self.label_10.raise_()
        self.lbPaciente.raise_()
        self.lbComentarios.raise_()
        self.lbTipo.raise_()
        self.lbFecha.raise_()
        self.lbIdentificador.raise_()
        self.label_5.raise_()
        self.lbMetaAlcanza.raise_()
        self.lbEjercicio_3.raise_()
        self.lbMetaPropuesta.raise_()
        self.label_7.raise_()
        self.btnAbrirGrafico.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.label_12.raise_()
        self.lbFecha_2.raise_()
        self.lbTipo_2.raise_()
        self.label1_2.raise_()
        self.groupBox.raise_()

        self.retranslateUi(ReporteEspecifico)
        QtCore.QMetaObject.connectSlotsByName(ReporteEspecifico)

    def retranslateUi(self, ReporteEspecifico):
        _translate = QtCore.QCoreApplication.translate
        ReporteEspecifico.setWindowTitle(_translate("ReporteEspecifico", "Reporte de paciente"))
        self.label.setText(_translate("ReporteEspecifico", "Reporte:"))
        self.label1.setText(_translate("ReporteEspecifico", "Tipo de ejercicio:"))
        self.label_2.setText(_translate("ReporteEspecifico", "Fecha:"))
        self.label_3.setText(_translate("ReporteEspecifico", "Tipo de onda:"))
        self.lbTipoOnda.setText(_translate("ReporteEspecifico", "xxxxxxxxxxxx"))
        self.label_4.setText(_translate("ReporteEspecifico", "Dracion: "))
        self.btnVideo.setText(_translate("ReporteEspecifico", "Visualizar Ondas"))
        self.btnReportes.setText(_translate("ReporteEspecifico", "Visualizar Reporte"))
        self.btnEmviarReporte.setText(_translate("ReporteEspecifico", "Imprimir Reporte"))
        self.label_6.setText(_translate("ReporteEspecifico", "Terapeuta: "))
        self.label_9.setText(_translate("ReporteEspecifico", "Tutor: "))
        self.lbDuracion.setText(_translate("ReporteEspecifico", "xxxxxxxxxxx"))
        self.lbTerapeuta.setText(_translate("ReporteEspecifico", "xxxxxxxxxxxxxxx"))
        self.lbTutor.setText(_translate("ReporteEspecifico", "Sin_Tutor"))
        self.label_10.setText(_translate("ReporteEspecifico", "Paciente:"))
        self.lbPaciente.setText(_translate("ReporteEspecifico", "xxxxxxxxxxxx"))
        self.lbTipo.setText(_translate("ReporteEspecifico", "xxxxxxxxxxx"))
        self.lbFecha.setText(_translate("ReporteEspecifico", "xxxxxxxxxxxxxxxxxxxxxxx"))
        self.lbIdentificador.setText(_translate("ReporteEspecifico", "Numero"))
        self.label_5.setText(_translate("ReporteEspecifico", "Meta alcanzada:"))
        self.lbMetaAlcanza.setText(_translate("ReporteEspecifico", "xx"))
        self.lbEjercicio_3.setText(_translate("ReporteEspecifico", "de"))
        self.lbMetaPropuesta.setText(_translate("ReporteEspecifico", "xx"))
        self.btnAbrirGrafico.setText(_translate("ReporteEspecifico", "Visualizar Grafico"))
        self.label_11.setText(_translate("ReporteEspecifico", "Datos de un Reporte especifico"))
        self.label_12.setText(_translate("ReporteEspecifico", "Edad:"))
        self.lbFecha_2.setText(_translate("ReporteEspecifico", "xxxxxxxxxxxx"))
        self.lbTipo_2.setText(_translate("ReporteEspecifico", "Nombre de ejercicio:"))
        self.label1_2.setText(_translate("ReporteEspecifico", "Nombre de ejercicio:"))
        self.groupBox.setTitle(_translate("ReporteEspecifico", "Tipo de Grafico"))
        self.rbGrafLIneal.setText(_translate("ReporteEspecifico", "Lineal"))
        self.rbGrafBarras.setText(_translate("ReporteEspecifico", "Barras"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReporteEspecifico = QtWidgets.QDialog()
    ui = Ui_ReporteEspecifico()
    ui.setupUi(ReporteEspecifico)
    ReporteEspecifico.show()
    sys.exit(app.exec_())

