# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'terapiaNeurofeedback.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import vistas.images

class Ui_TerapiaNeurofeedback(object):
    def setupUi(self, TerapiaNeurofeedback):
        TerapiaNeurofeedback.setObjectName("TerapiaNeurofeedback")
        TerapiaNeurofeedback.resize(1000, 705)
        TerapiaNeurofeedback.setMinimumSize(QtCore.QSize(1000, 705))
        TerapiaNeurofeedback.setMaximumSize(QtCore.QSize(1000, 724))
        self.label_2 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_2.setGeometry(QtCore.QRect(440, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cbPaciente = QtWidgets.QComboBox(TerapiaNeurofeedback)
        self.cbPaciente.setGeometry(QtCore.QRect(510, 120, 181, 31))
        self.cbPaciente.setObjectName("cbPaciente")
        self.cbPaciente.addItem("")
        self.cbPaciente.addItem("")
        self.cbPaciente.addItem("")
        self.label_4 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_4.setGeometry(QtCore.QRect(230, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cbRobot = QtWidgets.QComboBox(TerapiaNeurofeedback)
        self.cbRobot.setGeometry(QtCore.QRect(280, 120, 131, 31))
        self.cbRobot.setObjectName("cbRobot")
        self.cbRobot.addItem("")
        self.cbRobot.addItem("")
        self.cbRobot.addItem("")
        self.btbCapturarObservaciones = QtWidgets.QPushButton(TerapiaNeurofeedback)
        self.btbCapturarObservaciones.setGeometry(QtCore.QRect(40, 300, 161, 31))
        self.btbCapturarObservaciones.setStyleSheet("background-color: rgb(182, 181, 203);")
        self.btbCapturarObservaciones.setObjectName("btbCapturarObservaciones")
        self.labelComandosMentales = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.labelComandosMentales.setGeometry(QtCore.QRect(240, 660, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelComandosMentales.setFont(font)
        self.labelComandosMentales.setObjectName("labelComandosMentales")
        self.labelEventoDrone = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.labelEventoDrone.setGeometry(QtCore.QRect(500, 660, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelEventoDrone.setFont(font)
        self.labelEventoDrone.setObjectName("labelEventoDrone")
        self.label_11 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_11.setGeometry(QtCore.QRect(390, 580, 111, 71))
        self.label_11.setStyleSheet("image: url(:/newPrefix/EjerElevar.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_12.setGeometry(QtCore.QRect(230, 220, 461, 441))
        self.label_12.setStyleSheet("background-color: rgb(162, 175, 188);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.progressBar_2 = QtWidgets.QProgressBar(TerapiaNeurofeedback)
        self.progressBar_2.setGeometry(QtCore.QRect(130, 665, 101, 20))
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(TerapiaNeurofeedback)
        self.progressBar_3.setGeometry(QtCore.QRect(830, 665, 141, 20))
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_13 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_13.setGeometry(QtCore.QRect(710, 660, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.groupBox = QtWidgets.QGroupBox(TerapiaNeurofeedback)
        self.groupBox.setGeometry(QtCore.QRect(840, 400, 121, 81))
        self.groupBox.setObjectName("groupBox")
        self.rbInivitorio = QtWidgets.QRadioButton(self.groupBox)
        self.rbInivitorio.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.rbInivitorio.setObjectName("rbInivitorio")
        self.rdbExitatorio = QtWidgets.QRadioButton(self.groupBox)
        self.rdbExitatorio.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.rdbExitatorio.setChecked(True)
        self.rdbExitatorio.setObjectName("rdbExitatorio")
        self.cbBanda = QtWidgets.QComboBox(TerapiaNeurofeedback)
        self.cbBanda.setGeometry(QtCore.QRect(840, 360, 121, 21))
        self.cbBanda.setObjectName("cbBanda")
        self.cbBanda.addItem("")
        self.cbBanda.addItem("")
        self.cbBanda.addItem("")
        self.cbBanda.addItem("")
        self.cbBanda.addItem("")
        self.cbBanda.addItem("")
        self.progressBar_4 = QtWidgets.QProgressBar(TerapiaNeurofeedback)
        self.progressBar_4.setGeometry(QtCore.QRect(710, 220, 81, 400))
        self.progressBar_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_4.setStyleSheet("QProgressBar::chunk \"\n"
"                                            \"{\"\n"
"                                            \"background-color: orange;\"\n"
"                                            \"}\n"
"\n"
"")
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setTextVisible(True)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.label_16 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_16.setGeometry(QtCore.QRect(230, 160, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.cbPista = QtWidgets.QComboBox(TerapiaNeurofeedback)
        self.cbPista.setGeometry(QtCore.QRect(280, 160, 131, 31))
        self.cbPista.setObjectName("cbPista")
        self.cbPista.addItem("")
        self.cbPista.addItem("")
        self.cbPista.addItem("")
        self.cbPista.addItem("")
        self.cbPista.addItem("")
        self.label_17 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_17.setGeometry(QtCore.QRect(20, 660, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_14.setGeometry(QtCore.QRect(840, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_18.setGeometry(QtCore.QRect(840, 250, 121, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("font: 63 20pt \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(200, 198, 223);")
        self.label_18.setObjectName("label_18")
        self.frame = QtWidgets.QFrame(TerapiaNeurofeedback)
        self.frame.setGeometry(QtCore.QRect(-20, 0, 1021, 81))
        self.frame.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 0, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(910, 10, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("image: url(:/newPrefix/salud-mental.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(40, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(180, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(680, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_4 = QtWidgets.QFrame(TerapiaNeurofeedback)
        self.frame_4.setGeometry(QtCore.QRect(0, 80, 1001, 10))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 10))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label.setGeometry(QtCore.QRect(0, 90, 1010, 641))
        self.label.setMinimumSize(QtCore.QSize(1010, 590))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_7.setGeometry(QtCore.QRect(440, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cbEjercicio = QtWidgets.QComboBox(TerapiaNeurofeedback)
        self.cbEjercicio.setGeometry(QtCore.QRect(510, 160, 181, 31))
        self.cbEjercicio.setObjectName("cbEjercicio")
        self.cbEjercicio.addItem("")
        self.cbEjercicio.addItem("")
        self.cbEjercicio.addItem("")
        self.btnIniciarTerapia = QtWidgets.QPushButton(TerapiaNeurofeedback)
        self.btnIniciarTerapia.setEnabled(False)
        self.btnIniciarTerapia.setGeometry(QtCore.QRect(40, 220, 161, 31))
        self.btnIniciarTerapia.setStyleSheet("background-color: rgb(182, 181, 203);")
        self.btnIniciarTerapia.setObjectName("btnIniciarTerapia")
        self.btnActivarEmotiv = QtWidgets.QPushButton(TerapiaNeurofeedback)
        self.btnActivarEmotiv.setGeometry(QtCore.QRect(40, 260, 161, 31))
        self.btnActivarEmotiv.setStyleSheet("background-color: rgb(182, 181, 203);")
        self.btnActivarEmotiv.setObjectName("btnActivarEmotiv")
        self.lbMinutos = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.lbMinutos.setGeometry(QtCore.QRect(850, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lbMinutos.setFont(font)
        self.lbMinutos.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(200, 198, 223);")
        self.lbMinutos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMinutos.setObjectName("lbMinutos")
        self.lbUmbral = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.lbUmbral.setGeometry(QtCore.QRect(670, 470, 161, 91))
        self.lbUmbral.setStyleSheet("image: url(:/newPrefix/lineroja.png);")
        self.lbUmbral.setText("")
        self.lbUmbral.setObjectName("lbUmbral")
        self.label_20 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_20.setGeometry(QtCore.QRect(490, 270, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.spinBoxUmbral = QtWidgets.QSpinBox(TerapiaNeurofeedback)
        self.spinBoxUmbral.setGeometry(QtCore.QRect(840, 610, 121, 31))
        self.spinBoxUmbral.setObjectName("spinBoxUmbral")
        self.label_19 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_19.setGeometry(QtCore.QRect(840, 590, 121, 16))
        self.label_19.setObjectName("label_19")
        self.groupBox_2 = QtWidgets.QGroupBox(TerapiaNeurofeedback)
        self.groupBox_2.setGeometry(QtCore.QRect(840, 490, 121, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rbUmbralAutomatico = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbUmbralAutomatico.setGeometry(QtCore.QRect(10, 30, 95, 20))
        self.rbUmbralAutomatico.setChecked(True)
        self.rbUmbralAutomatico.setObjectName("rbUmbralAutomatico")
        self.rdUmbralManual = QtWidgets.QRadioButton(self.groupBox_2)
        self.rdUmbralManual.setGeometry(QtCore.QRect(10, 60, 95, 20))
        self.rdUmbralManual.setCheckable(True)
        self.rdUmbralManual.setChecked(False)
        self.rdUmbralManual.setObjectName("rdUmbralManual")
        self.label_21 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_21.setGeometry(QtCore.QRect(840, 340, 81, 16))
        self.label_21.setObjectName("label_21")
        self.label_8 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_8.setGeometry(QtCore.QRect(710, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_22 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_22.setGeometry(QtCore.QRect(710, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_25.setGeometry(QtCore.QRect(40, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_9 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_9.setGeometry(QtCore.QRect(40, 160, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.groupBox_3 = QtWidgets.QGroupBox(TerapiaNeurofeedback)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 350, 201, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnElevarDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnElevarDrone.setEnabled(True)
        self.btnElevarDrone.setGeometry(QtCore.QRect(20, 90, 161, 31))
        self.btnElevarDrone.setObjectName("btnElevarDrone")
        self.btnDecenderDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDecenderDrone.setEnabled(True)
        self.btnDecenderDrone.setGeometry(QtCore.QRect(20, 130, 161, 28))
        self.btnDecenderDrone.setObjectName("btnDecenderDrone")
        self.rotarContraRelocj = QtWidgets.QPushButton(self.groupBox_3)
        self.rotarContraRelocj.setGeometry(QtCore.QRect(30, 170, 31, 31))
        self.rotarContraRelocj.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/contraReloj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotarContraRelocj.setIcon(icon)
        self.rotarContraRelocj.setObjectName("rotarContraRelocj")
        self.btnDerechaDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnDerechaDrone.setEnabled(True)
        self.btnDerechaDrone.setGeometry(QtCore.QRect(130, 205, 31, 41))
        self.btnDerechaDrone.setObjectName("btnDerechaDrone")
        self.btnAdelanteDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAdelanteDrone.setEnabled(True)
        self.btnAdelanteDrone.setGeometry(QtCore.QRect(75, 170, 41, 31))
        self.btnAdelanteDrone.setObjectName("btnAdelanteDrone")
        self.btnAterrizarDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAterrizarDrone.setEnabled(True)
        self.btnAterrizarDrone.setGeometry(QtCore.QRect(65, 205, 61, 41))
        self.btnAterrizarDrone.setStyleSheet("")
        self.btnAterrizarDrone.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/despegar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAterrizarDrone.setIcon(icon1)
        self.btnAterrizarDrone.setIconSize(QtCore.QSize(60, 60))
        self.btnAterrizarDrone.setObjectName("btnAterrizarDrone")
        self.btnIsquierdaDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnIsquierdaDrone.setEnabled(True)
        self.btnIsquierdaDrone.setGeometry(QtCore.QRect(30, 205, 31, 41))
        self.btnIsquierdaDrone.setObjectName("btnIsquierdaDrone")
        self.btnAtrasDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnAtrasDrone.setEnabled(True)
        self.btnAtrasDrone.setGeometry(QtCore.QRect(75, 250, 41, 31))
        self.btnAtrasDrone.setObjectName("btnAtrasDrone")
        self.rotarRelocj = QtWidgets.QPushButton(self.groupBox_3)
        self.rotarRelocj.setGeometry(QtCore.QRect(130, 170, 31, 31))
        self.rotarRelocj.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/haciaReloj.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotarRelocj.setIcon(icon2)
        self.rotarRelocj.setObjectName("rotarRelocj")
        self.btnObtenerDrone = QtWidgets.QPushButton(self.groupBox_3)
        self.btnObtenerDrone.setGeometry(QtCore.QRect(20, 30, 161, 31))
        self.btnObtenerDrone.setStyleSheet("")
        self.btnObtenerDrone.setObjectName("btnObtenerDrone")
        self.progressBar_5 = QtWidgets.QProgressBar(TerapiaNeurofeedback)
        self.progressBar_5.setGeometry(QtCore.QRect(945, 250, 16, 71))
        self.progressBar_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_5.setStyleSheet("")
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setTextVisible(True)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_24 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_24.setGeometry(QtCore.QRect(490, 600, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_26.setGeometry(QtCore.QRect(230, 220, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("font: 87 9pt \"Arial Black\";")
        self.label_26.setObjectName("label_26")
        self.lineEdit = QtWidgets.QLineEdit(TerapiaNeurofeedback)
        self.lineEdit.setGeometry(QtCore.QRect(850, 170, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_27 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_27.setGeometry(QtCore.QRect(710, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_28.setGeometry(QtCore.QRect(490, 336, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_29.setGeometry(QtCore.QRect(490, 534, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_30.setGeometry(QtCore.QRect(490, 402, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(TerapiaNeurofeedback)
        self.label_31.setGeometry(QtCore.QRect(490, 468, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label.raise_()
        self.frame.raise_()
        self.label_12.raise_()
        self.label_2.raise_()
        self.cbPaciente.raise_()
        self.label_4.raise_()
        self.cbRobot.raise_()
        self.btbCapturarObservaciones.raise_()
        self.labelComandosMentales.raise_()
        self.labelEventoDrone.raise_()
        self.label_11.raise_()
        self.progressBar_2.raise_()
        self.progressBar_3.raise_()
        self.label_13.raise_()
        self.groupBox.raise_()
        self.cbBanda.raise_()
        self.progressBar_4.raise_()
        self.label_16.raise_()
        self.cbPista.raise_()
        self.label_17.raise_()
        self.label_14.raise_()
        self.label_18.raise_()
        self.frame_4.raise_()
        self.label_7.raise_()
        self.cbEjercicio.raise_()
        self.btnIniciarTerapia.raise_()
        self.btnActivarEmotiv.raise_()
        self.lbMinutos.raise_()
        self.lbUmbral.raise_()
        self.label_20.raise_()
        self.spinBoxUmbral.raise_()
        self.label_19.raise_()
        self.groupBox_2.raise_()
        self.label_21.raise_()
        self.label_8.raise_()
        self.label_22.raise_()
        self.label_25.raise_()
        self.label_9.raise_()
        self.groupBox_3.raise_()
        self.progressBar_5.raise_()
        self.label_24.raise_()
        self.label_26.raise_()
        self.lineEdit.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()

        self.retranslateUi(TerapiaNeurofeedback)
        QtCore.QMetaObject.connectSlotsByName(TerapiaNeurofeedback)

    def retranslateUi(self, TerapiaNeurofeedback):
        _translate = QtCore.QCoreApplication.translate
        TerapiaNeurofeedback.setWindowTitle(_translate("TerapiaNeurofeedback", "Terapia"))
        self.label_2.setText(_translate("TerapiaNeurofeedback", "Paciente:"))
        self.cbPaciente.setItemText(0, _translate("TerapiaNeurofeedback", "Paciente x"))
        self.cbPaciente.setItemText(1, _translate("TerapiaNeurofeedback", "Paciente y"))
        self.cbPaciente.setItemText(2, _translate("TerapiaNeurofeedback", "Paciente z"))
        self.label_4.setText(_translate("TerapiaNeurofeedback", "Dron:"))
        self.cbRobot.setItemText(0, _translate("TerapiaNeurofeedback", "Dron Be Boop"))
        self.cbRobot.setItemText(1, _translate("TerapiaNeurofeedback", "Dron Tello"))
        self.cbRobot.setItemText(2, _translate("TerapiaNeurofeedback", "Robot Lego"))
        self.btbCapturarObservaciones.setText(_translate("TerapiaNeurofeedback", "Capturar observaciones"))
        self.labelComandosMentales.setText(_translate("TerapiaNeurofeedback", "Istrucción"))
        self.labelEventoDrone.setText(_translate("TerapiaNeurofeedback", "Evento del Drone"))
        self.label_13.setText(_translate("TerapiaNeurofeedback", "Bateria del EEG:"))
        self.groupBox.setTitle(_translate("TerapiaNeurofeedback", "Tipo de Ejercicio"))
        self.rbInivitorio.setText(_translate("TerapiaNeurofeedback", "Inhibitorio"))
        self.rdbExitatorio.setText(_translate("TerapiaNeurofeedback", "Excitatorio"))
        self.cbBanda.setItemText(0, _translate("TerapiaNeurofeedback", "Theta/Beta"))
        self.cbBanda.setItemText(1, _translate("TerapiaNeurofeedback", "Beta Low"))
        self.cbBanda.setItemText(2, _translate("TerapiaNeurofeedback", "Theta"))
        self.cbBanda.setItemText(3, _translate("TerapiaNeurofeedback", "Beta High"))
        self.cbBanda.setItemText(4, _translate("TerapiaNeurofeedback", "Gama"))
        self.cbBanda.setItemText(5, _translate("TerapiaNeurofeedback", "Alfa"))
        self.label_16.setText(_translate("TerapiaNeurofeedback", "Pista:"))
        self.cbPista.setItemText(0, _translate("TerapiaNeurofeedback", "Sin Seleccion"))
        self.cbPista.setItemText(1, _translate("TerapiaNeurofeedback", "Sin Pista"))
        self.cbPista.setItemText(2, _translate("TerapiaNeurofeedback", "Pista 1"))
        self.cbPista.setItemText(3, _translate("TerapiaNeurofeedback", "Pista 2"))
        self.cbPista.setItemText(4, _translate("TerapiaNeurofeedback", "Pista 3"))
        self.label_17.setText(_translate("TerapiaNeurofeedback", "Bateria del Dron:"))
        self.label_14.setText(_translate("TerapiaNeurofeedback", "Puntos Obtenidos"))
        self.label_18.setText(_translate("TerapiaNeurofeedback", "     0"))
        self.label_3.setText(_translate("TerapiaNeurofeedback", "Nueva Terapia de tipo Neurofeedback"))
        self.label_6.setText(_translate("TerapiaNeurofeedback", "Terapeuta: nombre:"))
        self.label_15.setText(_translate("TerapiaNeurofeedback", "Monica Perales"))
        self.label_5.setText(_translate("TerapiaNeurofeedback", "Martes 17 de Octubre del 2021"))
        self.label_7.setText(_translate("TerapiaNeurofeedback", "Ejercicio:"))
        self.cbEjercicio.setItemText(0, _translate("TerapiaNeurofeedback", "Elevar drone"))
        self.cbEjercicio.setItemText(1, _translate("TerapiaNeurofeedback", "Decender Drone"))
        self.cbEjercicio.setItemText(2, _translate("TerapiaNeurofeedback", "Modo libre"))
        self.btnIniciarTerapia.setText(_translate("TerapiaNeurofeedback", "Iniciar terapia"))
        self.btnActivarEmotiv.setText(_translate("TerapiaNeurofeedback", "Grabar sesión"))
        self.lbMinutos.setText(_translate("TerapiaNeurofeedback", "00 : 00 "))
        self.label_20.setText(_translate("TerapiaNeurofeedback", "<--------------100%----------------"))
        self.spinBoxUmbral.setToolTip(_translate("TerapiaNeurofeedback", "Umbral de la terapia"))
        self.label_19.setText(_translate("TerapiaNeurofeedback", "Umbral de la terapia"))
        self.groupBox_2.setTitle(_translate("TerapiaNeurofeedback", "Tipo de umbral"))
        self.rbUmbralAutomatico.setText(_translate("TerapiaNeurofeedback", "Automatico"))
        self.rdUmbralManual.setText(_translate("TerapiaNeurofeedback", "Manual"))
        self.label_21.setText(_translate("TerapiaNeurofeedback", "Frecuencia"))
        self.label_8.setText(_translate("TerapiaNeurofeedback", "00.00 %"))
        self.label_22.setText(_translate("TerapiaNeurofeedback", "Tiempo de sesión:"))
        self.label_25.setText(_translate("TerapiaNeurofeedback", "Calidad de electrodos"))
        self.label_9.setText(_translate("TerapiaNeurofeedback", "00.00 %"))
        self.groupBox_3.setTitle(_translate("TerapiaNeurofeedback", "Control Manual de Dron"))
        self.btnElevarDrone.setToolTip(_translate("TerapiaNeurofeedback", "Subir Dron"))
        self.btnElevarDrone.setText(_translate("TerapiaNeurofeedback", "Subir Drone"))
        self.btnElevarDrone.setShortcut(_translate("TerapiaNeurofeedback", "W"))
        self.btnDecenderDrone.setToolTip(_translate("TerapiaNeurofeedback", "Bajar Dron"))
        self.btnDecenderDrone.setText(_translate("TerapiaNeurofeedback", "Bajar Drone"))
        self.btnDecenderDrone.setShortcut(_translate("TerapiaNeurofeedback", "S"))
        self.rotarContraRelocj.setToolTip(_translate("TerapiaNeurofeedback", "Girar Izquierdad Dron"))
        self.rotarContraRelocj.setShortcut(_translate("TerapiaNeurofeedback", "A"))
        self.btnDerechaDrone.setToolTip(_translate("TerapiaNeurofeedback", "Derecha Dron"))
        self.btnDerechaDrone.setText(_translate("TerapiaNeurofeedback", ">"))
        self.btnDerechaDrone.setShortcut(_translate("TerapiaNeurofeedback", "Right"))
        self.btnAdelanteDrone.setToolTip(_translate("TerapiaNeurofeedback", "Adelante Dron"))
        self.btnAdelanteDrone.setText(_translate("TerapiaNeurofeedback", "^"))
        self.btnAdelanteDrone.setShortcut(_translate("TerapiaNeurofeedback", "Up"))
        self.btnAterrizarDrone.setToolTip(_translate("TerapiaNeurofeedback", "Despegar o Aterrizar Dron"))
        self.btnAterrizarDrone.setShortcut(_translate("TerapiaNeurofeedback", "Space"))
        self.btnIsquierdaDrone.setToolTip(_translate("TerapiaNeurofeedback", "Izquierda Dron"))
        self.btnIsquierdaDrone.setText(_translate("TerapiaNeurofeedback", "<"))
        self.btnIsquierdaDrone.setShortcut(_translate("TerapiaNeurofeedback", "Left"))
        self.btnAtrasDrone.setToolTip(_translate("TerapiaNeurofeedback", "Atras Dron"))
        self.btnAtrasDrone.setText(_translate("TerapiaNeurofeedback", "v"))
        self.btnAtrasDrone.setShortcut(_translate("TerapiaNeurofeedback", "Down"))
        self.rotarRelocj.setToolTip(_translate("TerapiaNeurofeedback", "Girar derecha Dron"))
        self.rotarRelocj.setShortcut(_translate("TerapiaNeurofeedback", "D"))
        self.btnObtenerDrone.setText(_translate("TerapiaNeurofeedback", "Obtener Control Total"))
        self.label_24.setText(_translate("TerapiaNeurofeedback", "<---------------0%-----------------"))
        self.label_26.setText(_translate("TerapiaNeurofeedback", "Referencia de puntaje"))
        self.label_27.setText(_translate("TerapiaNeurofeedback", "Escala del umbral:"))
        self.label_28.setText(_translate("TerapiaNeurofeedback", "<--------------80%-----------------"))
        self.label_29.setText(_translate("TerapiaNeurofeedback", "<--------------20%-----------------"))
        self.label_30.setText(_translate("TerapiaNeurofeedback", "<--------------60%-----------------"))
        self.label_31.setText(_translate("TerapiaNeurofeedback", "<--------------40%-----------------"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TerapiaNeurofeedback = QtWidgets.QDialog()
    ui = Ui_TerapiaNeurofeedback()
    ui.setupUi(TerapiaNeurofeedback)
    TerapiaNeurofeedback.show()
    sys.exit(app.exec_())

