# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogAgregarTerapeuta(object):
    def setupUi(self, DialogAgregarTerapeuta):
        DialogAgregarTerapeuta.setObjectName("DialogAgregarTerapeuta")
        DialogAgregarTerapeuta.resize(504, 700)
        DialogAgregarTerapeuta.setMinimumSize(QtCore.QSize(490, 700))
        self.label = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label.setGeometry(QtCore.QRect(-10, -20, 541, 741))
        self.label.setMinimumSize(QtCore.QSize(480, 710))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(210, 220, 220), stop:1 rgba(100, 130, 190));\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.leCorreoElectronico = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leCorreoElectronico.setGeometry(QtCore.QRect(210, 470, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCorreoElectronico.setFont(font)
        self.leCorreoElectronico.setText("")
        self.leCorreoElectronico.setObjectName("leCorreoElectronico")
        self.leNombres = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leNombres.setGeometry(QtCore.QRect(210, 160, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leNombres.setFont(font)
        self.leNombres.setObjectName("leNombres")
        self.leCalle = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leCalle.setGeometry(QtCore.QRect(210, 380, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCalle.setFont(font)
        self.leCalle.setObjectName("leCalle")
        self.leLoclidad = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leLoclidad.setGeometry(QtCore.QRect(210, 350, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leLoclidad.setFont(font)
        self.leLoclidad.setObjectName("leLoclidad")
        self.label_5 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_17 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_17.setGeometry(QtCore.QRect(20, 500, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_22.setGeometry(QtCore.QRect(20, 590, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_16 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_16.setGeometry(QtCore.QRect(20, 470, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_18.setGeometry(QtCore.QRect(20, 260, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.leCofirnarPassword = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leCofirnarPassword.setGeometry(QtCore.QRect(210, 560, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCofirnarPassword.setFont(font)
        self.leCofirnarPassword.setText("")
        self.leCofirnarPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.leCofirnarPassword.setObjectName("leCofirnarPassword")
        self.leCodigoPostal = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leCodigoPostal.setGeometry(QtCore.QRect(210, 410, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leCodigoPostal.setFont(font)
        self.leCodigoPostal.setObjectName("leCodigoPostal")
        self.label_21 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_21.setGeometry(QtCore.QRect(20, 560, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.leNombreUsuario = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leNombreUsuario.setGeometry(QtCore.QRect(210, 500, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leNombreUsuario.setFont(font)
        self.leNombreUsuario.setObjectName("leNombreUsuario")
        self.btnCancelar = QtWidgets.QPushButton(DialogAgregarTerapeuta)
        self.btnCancelar.setGeometry(QtCore.QRect(160, 630, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCancelar.setFont(font)
        self.btnCancelar.setStyleSheet("background-color: rgb(255, 211, 160);\n"
"background-color: rgb(200, 198, 223);")
        self.btnCancelar.setObjectName("btnCancelar")
        self.leNumeroCalle = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leNumeroCalle.setGeometry(QtCore.QRect(360, 380, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leNumeroCalle.setFont(font)
        self.leNumeroCalle.setObjectName("leNumeroCalle")
        self.label_6 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.leNumeroContacto = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leNumeroContacto.setGeometry(QtCore.QRect(210, 440, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leNumeroContacto.setFont(font)
        self.leNumeroContacto.setObjectName("leNumeroContacto")
        self.btnRegistrar = QtWidgets.QPushButton(DialogAgregarTerapeuta)
        self.btnRegistrar.setGeometry(QtCore.QRect(30, 630, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnRegistrar.setFont(font)
        self.btnRegistrar.setStyleSheet("background-color: rgb(180, 255, 199);\n"
"background-color: rgb(200, 198, 223);")
        self.btnRegistrar.setObjectName("btnRegistrar")
        self.label_4 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lePassword = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.lePassword.setGeometry(QtCore.QRect(210, 530, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lePassword.setFont(font)
        self.lePassword.setText("")
        self.lePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lePassword.setObjectName("lePassword")
        self.label_19 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_19.setGeometry(QtCore.QRect(20, 530, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_20.setGeometry(QtCore.QRect(20, 500, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_11 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_11.setGeometry(QtCore.QRect(20, 380, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_9.setGeometry(QtCore.QRect(20, 290, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_15.setGeometry(QtCore.QRect(20, 190, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.leApellidoPaterno = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leApellidoPaterno.setGeometry(QtCore.QRect(210, 100, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leApellidoPaterno.setFont(font)
        self.leApellidoPaterno.setObjectName("leApellidoPaterno")
        self.leApellidoMaterno = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leApellidoMaterno.setGeometry(QtCore.QRect(210, 130, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leApellidoMaterno.setFont(font)
        self.leApellidoMaterno.setObjectName("leApellidoMaterno")
        self.label_14 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_14.setGeometry(QtCore.QRect(20, 440, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_12 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_12.setGeometry(QtCore.QRect(20, 320, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.dateEdit = QtWidgets.QDateEdit(DialogAgregarTerapeuta)
        self.dateEdit.setGeometry(QtCore.QRect(210, 230, 110, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(1921, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1920, 9, 26), QtCore.QTime(1, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.cbEstado = QtWidgets.QComboBox(DialogAgregarTerapeuta)
        self.cbEstado.setGeometry(QtCore.QRect(210, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbEstado.setFont(font)
        self.cbEstado.setObjectName("cbEstado")
        self.cbEstado.addItem("")
        self.leNacionalidad = QtWidgets.QLineEdit(DialogAgregarTerapeuta)
        self.leNacionalidad.setGeometry(QtCore.QRect(210, 260, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leNacionalidad.setFont(font)
        self.leNacionalidad.setObjectName("leNacionalidad")
        self.label_10 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_10.setGeometry(QtCore.QRect(20, 350, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btnVerPas_2 = QtWidgets.QPushButton(DialogAgregarTerapeuta)
        self.btnVerPas_2.setGeometry(QtCore.QRect(410, 560, 21, 21))
        self.btnVerPas_2.setStyleSheet("background-color: qconicalgradient(cx:0.488, cy:0.494318, angle:123.4, stop:0 rgba(0, 0, 0, 0));\n"
"border-image: url(:/newPrefix/vision.png);")
        self.btnVerPas_2.setText("")
        self.btnVerPas_2.setObjectName("btnVerPas_2")
        self.label_13 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_13.setGeometry(QtCore.QRect(20, 410, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(DialogAgregarTerapeuta)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cbMunicipio = QtWidgets.QComboBox(DialogAgregarTerapeuta)
        self.cbMunicipio.setGeometry(QtCore.QRect(210, 320, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbMunicipio.setFont(font)
        self.cbMunicipio.setObjectName("cbMunicipio")
        self.cbMunicipio.addItem("")
        self.btnVerPas_1 = QtWidgets.QPushButton(DialogAgregarTerapeuta)
        self.btnVerPas_1.setGeometry(QtCore.QRect(410, 530, 21, 21))
        self.btnVerPas_1.setStyleSheet("background-color: qconicalgradient(cx:0.488, cy:0.494318, angle:123.4, stop:0 rgba(0, 0, 0, 0));\n"
"border-image: url(:/newPrefix/vision.png);")
        self.btnVerPas_1.setText("")
        self.btnVerPas_1.setObjectName("btnVerPas_1")
        self.frame = QtWidgets.QFrame(DialogAgregarTerapeuta)
        self.frame.setGeometry(QtCore.QRect(0, 0, 531, 81))
        self.frame.setStyleSheet("background-color: rgb(200, 198, 223);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"font: 75 19pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setGeometry(QtCore.QRect(420, 10, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("image: url(:/newPrefix/terapeuta.png);")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.frame_2 = QtWidgets.QFrame(DialogAgregarTerapeuta)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 531, 8))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 8))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(214, 225, 229), stop:1 rgba(109, 130, 198));\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox = QtWidgets.QGroupBox(DialogAgregarTerapeuta)
        self.groupBox.setGeometry(QtCore.QRect(210, 180, 221, 41))
        self.groupBox.setObjectName("groupBox")
        self.rbFemenino = QtWidgets.QRadioButton(self.groupBox)
        self.rbFemenino.setGeometry(QtCore.QRect(124, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbFemenino.setFont(font)
        self.rbFemenino.setObjectName("rbFemenino")
        self.rbMasculino = QtWidgets.QRadioButton(self.groupBox)
        self.rbMasculino.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rbMasculino.setFont(font)
        self.rbMasculino.setObjectName("rbMasculino")
        self.checkBox = QtWidgets.QCheckBox(DialogAgregarTerapeuta)
        self.checkBox.setGeometry(QtCore.QRect(210, 590, 81, 20))
        self.checkBox.setObjectName("checkBox")
        self.radioButton = QtWidgets.QRadioButton(DialogAgregarTerapeuta)
        self.radioButton.setGeometry(QtCore.QRect(400, 240, 95, 20))
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(DialogAgregarTerapeuta)
        QtCore.QMetaObject.connectSlotsByName(DialogAgregarTerapeuta)

    def retranslateUi(self, DialogAgregarTerapeuta):
        _translate = QtCore.QCoreApplication.translate
        DialogAgregarTerapeuta.setWindowTitle(_translate("DialogAgregarTerapeuta", "Dialog"))
        self.label_3.setText(_translate("DialogAgregarTerapeuta", "Apellido Materno"))
        self.label_5.setText(_translate("DialogAgregarTerapeuta", "Fecha de nacimiento"))
        self.label_22.setText(_translate("DialogAgregarTerapeuta", "¿Es administrador?"))
        self.label_16.setText(_translate("DialogAgregarTerapeuta", "Correo electronico"))
        self.label_18.setText(_translate("DialogAgregarTerapeuta", "Nacionalidad"))
        self.label_21.setText(_translate("DialogAgregarTerapeuta", "Confirmar Contraseña"))
        self.btnCancelar.setText(_translate("DialogAgregarTerapeuta", "Cancelar"))
        self.btnRegistrar.setText(_translate("DialogAgregarTerapeuta", "Registrar"))
        self.label_4.setText(_translate("DialogAgregarTerapeuta", "Nombre(s)"))
        self.label_19.setText(_translate("DialogAgregarTerapeuta", "Contraseña"))
        self.label_20.setText(_translate("DialogAgregarTerapeuta", "Nombre de Usuario"))
        self.label_11.setText(_translate("DialogAgregarTerapeuta", "Calle y número"))
        self.label_9.setText(_translate("DialogAgregarTerapeuta", "Estado"))
        self.label_15.setText(_translate("DialogAgregarTerapeuta", "Genero"))
        self.label_14.setText(_translate("DialogAgregarTerapeuta", "Numero de contacto"))
        self.label_12.setText(_translate("DialogAgregarTerapeuta", "Municipio"))
        self.cbEstado.setItemText(0, _translate("DialogAgregarTerapeuta", "Jalisco"))
        self.label_10.setText(_translate("DialogAgregarTerapeuta", "Localidad"))
        self.label_13.setText(_translate("DialogAgregarTerapeuta", "Codigo postal"))
        self.label_7.setText(_translate("DialogAgregarTerapeuta", "Apellido paterno"))
        self.cbMunicipio.setItemText(0, _translate("DialogAgregarTerapeuta", "Ameca"))
        self.label_2.setText(_translate("DialogAgregarTerapeuta", "Ingresa los datos del Terapeuta"))
        self.groupBox.setTitle(_translate("DialogAgregarTerapeuta", "Genero"))
        self.rbFemenino.setText(_translate("DialogAgregarTerapeuta", "Femenino"))
        self.rbMasculino.setText(_translate("DialogAgregarTerapeuta", "Masculino"))
        self.checkBox.setText(_translate("DialogAgregarTerapeuta", "Admin"))
        self.radioButton.setText(_translate("DialogAgregarTerapeuta", "RadioButton"))

import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAgregarTerapeuta = QtWidgets.QDialog()
    ui = Ui_DialogAgregarTerapeuta()
    ui.setupUi(DialogAgregarTerapeuta)
    DialogAgregarTerapeuta.show()
    sys.exit(app.exec_())

